### ISSUE TITLE
The method .numpy discards -inf and inf on x and y axis of imported TH2D

### ISSUE THREAD

**Issue by giammi56** [scikit-hep/uproot4#100]
I tried on TH2D graphs and upon the conversion of an imported TH2D using myTH2D.numpy(), the arrays myTH2D.index (y-axis) and myTH2D.column (x-axis) have their dimension **INCREASED** by 1 respect to the respective rows and columns of the matrix myTH2.values (z-axis).

**Comment by jpivarski** [comment]
Could it be the overflow bin? In Uproot 3, there's a distinction between "values" (no overflow bins) and "allvalues" (with overflow bins), and in Uproot 4, they just always have overflow bins.

Just last week, Raymond Ehlers did a detailed study of the bin alignments in PR scikit-hep/uproot4#97.

**Comment by giammi56** [comment]
To be sure it is not realted with the over- and underflow bins I tried to import the following image:

![image](https://user-images.githubusercontent.com/11757284/93094999-deb8a880-f6a2-11ea-9759-d822e8ff2830.png)

`myTH2histo.pandas()`

```
MultiIndex([([-inf, -1.5),                               [-inf, -1.5)),
            ([-inf, -1.5),                [-1.5, -1.4863636363636363)),
            ([-inf, -1.5), [-1.4863636363636363, -1.4727272727272727)),
            ([-inf, -1.5),  [-1.4727272727272727, -1.459090909090909)),
            ([-inf, -1.5),  [-1.459090909090909, -1.4454545454545455)),
            ([-inf, -1.5), [-1.4454545454545455, -1.4318181818181819)),
            ([-inf, -1.5), [-1.4318181818181819, -1.4181818181818182)),
            ([-inf, -1.5), [-1.4181818181818182, -1.4045454545454545)),
            ([-inf, -1.5), [-1.4045454545454545, -1.3909090909090909)),
            ([-inf, -1.5), [-1.3909090909090909, -1.3772727272727272)),
            ...
            (  [1.5, inf),    [1.377272727272727, 1.3909090909090907)),
            (  [1.5, inf),   [1.3909090909090907, 1.4045454545454543)),
            (  [1.5, inf),    [1.4045454545454543, 1.418181818181818)),
            (  [1.5, inf),    [1.418181818181818, 1.4318181818181817)),
            (  [1.5, inf),   [1.4318181818181817, 1.4454545454545453)),
            (  [1.5, inf),    [1.4454545454545453, 1.459090909090909)),
            (  [1.5, inf),    [1.459090909090909, 1.4727272727272727)),
            (  [1.5, inf),   [1.4727272727272727, 1.4863636363636363)),
            (  [1.5, inf),                  [1.4863636363636363, 1.5)),
            (  [1.5, inf),                                 [1.5, inf))],
           names=['p_x [a.u.]', 'p_y [a.u.]'], length=49284)
```

but here is the issue:

pinumpy = myTH2Dhisto.numpy() 
z = pinumpy[0] # ndarray
x = pinumpy[1][0][0] # ndarray
y = pinumpy[1][0][1] # ndarray
print(z.shape, x.shape, y.shape)

(220, 220) (221,) (221,)

it is INCREASED by 1

**Comment by jpivarski** [comment]
`pinumpy` is already a NumPy array, right? I'm having trouble seeing how you get the above: different elements of a single NumPy array can't have different shapes like that.

Could you print out `type(pinumpy)` and `pinumpy.shape`?

**Comment by jpivarski** [comment]
Oh! `pinumpy` is a tuple! Okay, I'm no longer confused about that.

**Comment by giammi56** [comment]
Yes, pinumpy is a `tuple` made of `ndarray` . Have I stated the problem in the right way?

**Comment by jpivarski** [comment]
The format of `myTH2Dhisto.numpy()` is supposed to match the output of [np.histogram](https://numpy.org/doc/stable/reference/generated/numpy.histogram.html), [np.histogram2d](https://numpy.org/doc/stable/reference/generated/numpy.histogram2d.html), and [np.histogramdd](https://numpy.org/doc/stable/reference/generated/numpy.histogramdd.html). There was some disagreement about whether 2d histograms should look like `np.histogram2d` or `np.histogramdd`; I don't remember where that landed.

In the NumPy examples, the array of edges is _supposed_ to be one longer than the number of bins because they represent the fenceposts surrounding bin content. Libraries that expect data from NumPy histograms should expect (require!) that.

**Comment by jpivarski** [comment]
Oh—you mean plotting libraries that don't expect the data to be histogram data, just x-y points to plot.

In that case, you want to use `(x[1:] - x[:-1])/2` and `(y[1:] - y[:-1])/2` instead of `x` and `y` because if you're plotting the histogram data as an x-y plot, you want to use the centers, not the edges, of the bins. The same would be true if you got the data from `np.histogram`, etc.

**Comment by jpivarski** [comment]
If centering the edges is what you needed and it's working for you, just let me know so I can close the issue. Thanks!

**Comment by giammi56** [comment]
The only plotting method directly working (i.e. having x,y,z as inputs) is `hep.hist2dplot(z,x,y)`.
`plt.imshow()` works with` extent=[x[0],x[-1],y[0],y[-1]]` therefore specifying the x and y axis extent
`plt.contourf(x,y,z)` requires the dimensions to match.

The problem is not to find the centre, it is to reduce the lenght of one value:

print(x)

[-1.5        -1.48636364 -1.47272727 -1.45909091 -1.44545455 -1.43181818
 -1.41818182 -1.40454545 -1.39090909 -1.37727273 -1.36363636 -1.35
 -1.33636364 -1.32272727 -1.30909091 -1.29545455 -1.28181818 -1.26818182
 -1.25454545 -1.24090909 -1.22727273 -1.21363636 -1.2        -1.18636364
 -1.17272727 -1.15909091 -1.14545455 -1.13181818 -1.11818182 -1.10454545
 -1.09090909 -1.07727273 -1.06363636 -1.05       -1.03636364 -1.02272727
 -1.00909091 -0.99545455 -0.98181818 -0.96818182 -0.95454545 -0.94090909
 -0.92727273 -0.91363636 -0.9        -0.88636364 -0.87272727 -0.85909091
 -0.84545455 -0.83181818 -0.81818182 -0.80454545 -0.79090909 -0.77727273
 -0.76363636 -0.75       -0.73636364 -0.72272727 -0.70909091 -0.69545455
 -0.68181818 -0.66818182 -0.65454545 -0.64090909 -0.62727273 -0.61363636
 -0.6        -0.58636364 -0.57272727 -0.55909091 -0.54545455 -0.53181818
 -0.51818182 -0.50454545 -0.49090909 -0.47727273 -0.46363636 -0.45
 -0.43636364 -0.42272727 -0.40909091 -0.39545455 -0.38181818 -0.36818182
 -0.35454545 -0.34090909 -0.32727273 -0.31363636 -0.3        -0.28636364
 -0.27272727 -0.25909091 -0.24545455 -0.23181818 -0.21818182 -0.20454545
 -0.19090909 -0.17727273 -0.16363636 -0.15       -0.13636364 -0.12272727
 -0.10909091 -0.09545455 -0.08181818 -0.06818182 -0.05454545 -0.04090909
 -0.02727273 -0.01363636  0.          0.01363636  0.02727273  0.04090909
  0.05454545  0.06818182  0.08181818  0.09545455  0.10909091  0.12272727
  0.13636364  0.15        0.16363636  0.17727273  0.19090909  0.20454545
  0.21818182  0.23181818  0.24545455  0.25909091  0.27272727  0.28636364
  0.3         0.31363636  0.32727273  0.34090909  0.35454545  0.36818182
  0.38181818  0.39545455  0.40909091  0.42272727  0.43636364  0.45
  0.46363636  0.47727273  0.49090909  0.50454545  0.51818182  0.53181818
  0.54545455  0.55909091  0.57272727  0.58636364  0.6         0.61363636
  0.62727273  0.64090909  0.65454545  0.66818182  0.68181818  0.69545455
  0.70909091  0.72272727  0.73636364  0.75        0.76363636  0.77727273
  0.79090909  0.80454545  0.81818182  0.83181818  0.84545455  0.85909091
  0.87272727  0.88636364  0.9         0.91363636  0.92727273  0.94090909
  0.95454545  0.96818182  0.98181818  0.99545455  1.00909091  1.02272727
  1.03636364  1.05        1.06363636  1.07727273  1.09090909  1.10454545
  1.11818182  1.13181818  1.14545455  1.15909091  1.17272727  1.18636364
  1.2         1.21363636  1.22727273  1.24090909  1.25454545  1.26818182
  1.28181818  1.29545455  1.30909091  1.32272727  1.33636364  1.35
  1.36363636  1.37727273  1.39090909  1.40454545  1.41818182  1.43181818
  1.44545455  1.45909091  1.47272727  1.48636364  1.5       ]

and

print(x.shape)

(221,)

**Comment by jpivarski** [comment]
I mean if `x` has length `221`, `(x[1:] + x[:-1])/2` will have length `220`. The expression is implicitly a loop (and much faster than a for loop, though that may be irrelevant here).

I didn't see a StackOverflow link, but that's a good place to start. The issue you're having is with NumPy, how to use slicing to get an array of the right dimensions. The bin edges have a length one greater than the bin contents because of the Fencepost Principle, and that's because it's qualitatively different than the thing you want (edges rather than centers). NumPy's syntax lets you express implicit loops simply, so that you can get from edges to centers in a tight expression like `(x[1:] + x[:-1])/2`. (The `x[1:]` drops the first edge, the `x[:-1]` drops the last edge, `x[1:] + x[:-1]` adds the remaining ones element by element (the implicit loop), and dividing by two gives the mean of each.)

By writing `(x[1:] + x[:-1])/2` out in words, I realized that I had meant a `+`, not a `-`. Sorry!
