### ISSUE TITLE
flow option for values/edges

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/uproot4#104]
Would be convenient to have flow option for values/edges methods on THX matching with the `to_numpy()` method, esp when porting uproot3 code.

**Comment by jpivarski** [comment]
The interface here will be made identical to the interface chosen by boost-histogram and hist. I'm waiting for @henryiii and @HDembinski to finalize a library-independent API for `edges`, `values`, (`errors` or `variances`), and `to_numpy`, and then I'll be putting exactly the same API into Uproot. Since this is a request for a feature in that API, I've mentioned them here so they're aware of it.

**Comment by andrzejnovak** [comment]
Is this the relevant issue to keep track of https://github.com/scikit-hep/hist/issues/64 ?

**Comment by jpivarski** [comment]
> Is this the relevant issue to keep track of [scikit-hep/hist#64](https://github.com/scikit-hep/hist/issues/64) ?

This issue has been spread all over the place. It needs to be centralized, and ideally that would be in one of the two histogramming libraries. Maybe that would be a moot point by resolving it on a shorter timescale. (It sounded to me today like @henryiii was close.)

**Comment by jpivarski** [comment]
For example, #50 is another reference to this issue. So are scikit-hep/uproot#511 and scikit-hep/uproot#502.

**Comment by jpivarski** [comment]
All of these duplicates will all go into #167, where this interface will get figured out, once and for all.
