### ISSUE TITLE
Superfluous print statement in iterate

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot4#108]
#101 introduced a `print` statement in `iterate`.  Affects `uproot4` versions >0.0.22. I believe this was added for debugging purposes, but is not meant to be in the package.

Reproduce: 
- download https://github.com/scikit-hep/scikit-hep-testdata/raw/master/src/skhep_testdata/data/uproot-HZZ.root
- run the script:

```python
import uproot4

for _ in uproot4.iterate("uproot-HZZ.root"): pass
```

output:
```
uproot-HZZ.root 0
```

due to https://github.com/scikit-hep/uproot4/blob/1accbe3a70eda72cad954187291ddaec5f36e22d/uproot4/behaviors/TBranch.py#L213

**Comment by jpivarski** [comment]
Thanks—I'll fix it in about 15 minutes.

**Comment by jpivarski** [comment]
Nope—you're faster than me! I'll approve your PR when the tests pass, and then deploy a new version.

**Comment by alexander-held** [comment]
Thanks! I thought it was an easy enough change that I can just submit a PR directly, hope that's fine. :)

**Comment by henryiii** [comment]
Recommendation (since I've had this happen to me **twice** now in boost-histogram): add a flake8 check for print statements in the source. https://scikit-hep.org/developer/style#flake8

**Comment by jpivarski** [comment]
I was remembering your issue with that earlier and I was wondering if you were going to mention it.

~I struggled through the instructions on that page because it didn't say that I need to install [flake8-print](https://pypi.org/project/flake8-print/).~ I've got that now and the PR is #110.

Ack! It _does_ say that I need flake8-print. How did I not see that? It was right in the spot where I was looking. Somehow, I was thinking that it was flake8-naming. That's the weirdest off-by-one error I've experienced. (flake8-naming was on the previous line: I scanned wrong.)

False alarm: the documentation is fine. I can't read.
