### ISSUE TITLE
Need behaviors (and possibly Models) for boost::histogram objects in ROOT files

### ISSUE THREAD

**Issue by chernals** [scikit-hep/uproot4#115]
Compared to `uproot3` I can properly deserialize a `boost::histogram` object that has been stored in a `ROOT` directory or branch.

However I end up with a totally opaque object.

I look at how you proceed for the `ROOT` histograms (using `member`) and wrapping it in a Python class.

However my objects (the boost histograms) have no member. 

Could you maybe point me in the right direction so that I could get these? I would be happy to contribute the "behavior" for these then.

**Comment by jpivarski** [comment]
I don't know how `boost::histogram` objects are serialized in ROOT. What does the object you get look like? Does the class have "Unknown" in its name? (If so, that means it was skipped, not deserialized.)

If the object was deserialized and the data is somewhere in one of the [Model](https://uproot4.readthedocs.io/en/latest/uproot4.model.Model.html) attributes, then you just need to define a submodule in [uproot4.models](https://uproot4.readthedocs.io/en/latest/uproot4.models.html), just like [TH1](https://uproot4.readthedocs.io/en/latest/uproot4.behaviors.TH1.TH1.html), etc.

If it was not deserialized (you have an "Unknown" model, a subclass of [UnknownClass](https://uproot4.readthedocs.io/en/latest/uproot4.model.UnknownClass.html)), then you'll need to add a custom model in [uproot4.models](https://uproot4.readthedocs.io/en/latest/uproot4.models.html).

The way it works is:

   1. When we see that an object in a ROOT file has a certain C++ class, we look in `uproot4.classes` (a dict) or [ReadOnlyFile.custom_classes](https://uproot4.readthedocs.io/en/latest/uproot4.reading.ReadOnlyFile.html#custom-classes) to find a Model for it. If we find one directly, we call [Model.read](https://uproot4.readthedocs.io/en/latest/uproot4.model.Model.html#read), passing it a pointer to the raw data at that point in the file. The Model is responsible for deserializing the raw data into an object.
   2. If there is no predefined Model, then we use the [ReadOnlyFile.streamers](https://uproot4.readthedocs.io/en/latest/uproot4.reading.ReadOnlyFile.html#streamers) to make such a class. The streamers have enough data to define the deserialization process.
   3. If the C++ class has a behavior defined in [uproot4.behaviors](https://uproot4.readthedocs.io/en/latest/uproot4.behaviors.html) (a module), then the newly generated classes are subclasses of that behavior.

So for example, we have predefined Models for [TTree](https://uproot4.readthedocs.io/en/latest/uproot4.models.TTree.Model_TTree_v20.html), which is a subclass of the [TTree behavior](https://uproot4.readthedocs.io/en/latest/uproot4.behaviors.TTree.TTree.html) by definition, so the TTree both knows how to deserialize itself and what user-facing methods it should have.

For another example, we don't have predefined Models for TH1*, so they're generated from the file's streamers. But we do have [behaviors for TH1](https://uproot4.readthedocs.io/en/latest/uproot4.behaviors.TH1.TH1.html) with the right names in the right places, so when new model classes are created for TH1*, they get all the user-facing methods they're supposed to have.

(To add just a little more complexity to this description, classes can have different versions. We only have predefined models for the most common TTree versions (from the last 5 years of ROOT versions). If we know about the class but not the version, we go to the file's streamers and generate a class with behaviors just like the case of not having any class information. In fact, we also need to fall back on this even for classes where we think we know the version because some files were generated with serialization patterns that don't agree with the standard definition of a given class version: most likely, they were made with custom compilations of ROOT. But it's the same mechanism: after failing with the first definition, we generate a new class from streamers and make it a subclass of the appropriate behaviors.)

**Comment by jpivarski** [comment]
This discussion moved to Gitter, but neither I nor @HDembinski could figure out how `boost::histogram` objects got saved to a ROOT file in the first place. If there's a standard serialization, then we can add Models to Uproot to read that serialization, but first we have to know what these objects are _supposed_ to look like.
