### ISSUE TITLE
XRootD source doesn't fall back to non-vector read

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#122]
In this CMS open data example, I cannot load a branch's array due to a NotImplementedError
```python
>>> import uproot4
>>> file = uproot4.open("root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/ZZTo4mu.root")
>>> file["Events/Muon_eta"].array(entry_stop=244800)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ncsmith/src/uproot4/uproot4/behaviors/TBranch.py", line 2017, in array
    _ranges_or_baskets_to_arrays(
  File "/Users/ncsmith/src/uproot4/uproot4/behaviors/TBranch.py", line 3180, in _ranges_or_baskets_to_arrays
    hasbranches._file.source.chunks(ranges, notifications=notifications)
  File "/Users/ncsmith/src/uproot4/uproot4/source/xrootd.py", line 263, in chunks
    raise NotImplementedError(
NotImplementedError: TODO: Probably need to fall back to a non-vector read
```
Can this be implemented?

**Comment by jpivarski** [comment]
Copying from Slack again:

This "probably" is because I don't understand the "max element size" logic here; it was written by @chrisburr.
However, you can test a non-vector read by setting `xrootd_handler=uproot4.MultithreadedXRootDSource`. This alternative XRootD source doesn't attempt a vector-read and makes separate XRootD connections in Python threads. The number of those Python threads is set by `num_workers` (by default, 1).

HTTP sources do a fallback from multi-part GET to many threads each doing one GET; this would be the same thing for XRootD. I just wasn't sure if the "max element size" failure was reason enough to do the fallback and wanted to get real use-case experience first.

**Comment by nsmith-** [comment]
Another workaround would be using the http endpoint `https://eospublichttp.cern.ch/eos/root-eos/cms_opendata_2012_nanoaod/ZZTo4mu.root` but there they don't have a host certificate that is trusted by default. Can I access the certificate verify option in the HTTP source somehow?

**Comment by jpivarski** [comment]
That would be another requested feature. It would go into

https://github.com/scikit-hep/uproot4/blob/7e42e2f71d9fb20dbfb12d177403b3b0839d0cc2/uproot4/source/http.py#L40

as an argument.
