### ISSUE TITLE
TTree indices awareness in uproot for faster data access from a file?

### ISSUE THREAD

**Issue by pibion** [scikit-hep/uproot4#125]
We're trying to use ROOT files as a cache for cut information, and right now we're selecting the data we need by iterating through the entire file.

I was wondering if uproot is aware of TTree indices and might be able to grab data more efficiently, or if that is on the uproot roadmap.

Adding @bloer since he's interested in this issue as well.

Thanks!

**Comment by jpivarski** [comment]
I don't think I know about this. Try printing out `ttree.all_members` or `ttree["some_branch"].all_members`, maybe with `minimal_ttree_metadata=False` passed to `uproot4.open`. If you see what you're looking for, we can build convenience methods around it.

**Comment by jpivarski** [comment]
This has been quiet for a while, but I'm going through issues now.

By "TTree indexes," do you mean any of the following?

   * `fIndexValues`
   * `fIndex`
   * `fTreeIndex`

Currently, we're not reading these values because they come at the end of the structure and we're not using them. But the `minimal_ttree_metadata` parameter controls that:

```python
>>> import uproot4
>>> import skhep_testdata
>>> f = uproot4.open(skhep_testdata.data_path("uproot-Zmumu.root"),
...                  minimal_ttree_metadata=False)
>>> f["events"].member("fIndexValues")
<TArrayD [] at 0x7fc53d3e8df0>
>>> f["events"].member("fIndex")
<TArrayI [] at 0x7fc53d3e8e50>
>>> f["events"].member("fTreeIndex")
None
```

If these are useful, I'll consider them non-minimal. What would you do with these arrays? Can you show me an example?

**Comment by jpivarski** [comment]
Let me know if you want to pursue this. By default, the `fIndexValues`, `fIndex`, and `fTreeIndex` quantities are not read; the `minimal_ttree_metadata=False` argument can turn them on.

If you know of a way that these quantities can be used, tell me and I'll (1) read them by default and (2) do whatever you have in mind.

For now, though, I'm going to close this issue because of the silence. (I use the open issues to look for work to do, so clutter is a problem. If you respond to an issue, even if it's closed, I do see it in my email inbox and will reopen the issue.)
