### ISSUE TITLE
multiprocessing and uproot4 

### ISSUE THREAD

**Issue by ramankhurana** [scikit-hep/uproot4#173]
Hello 

I am trying to run uproot4 parallel on multiple files but it seems to be stuck at reading the TTree from root files. It used to work for uproot 3 but not in uproot4. 

I found there are some possibilities to do parallel processing using uproot4.reading.open but i could not understand from documentation what exactly I should be doing to use it for multiple files in parallel. 

Thanks you.

**Comment by jpivarski** [comment]
There aren't supposed to be any constraints. Uproot (both versions) spawn threads, but it's possible for objects in a multiprocessing environment to spawn their own threads. You don't want to be passing objects derived from one open file from one process into another (something you should avoid in general because processes don't share memory or file handles), but it should be perfectly okay for processes in `multiprocessing` to each open their own files and work with them independently.

**Comment by ramankhurana** [comment]
Thanks for quick response as always. Yes indeed, I am not trying to pass any object from one thread to another, just to separate independent threads. 

I quote an example here but rootfile are in public area to do the test, if not possible I can share it somewhre on thw weblink, 
```
import uproot4
import awkward1 as ak
import multiprocessing as mp
from functools import partial

file_=["/afs/cern.ch/user/k/khurana/public/test.root", "/afs/cern.ch/user/k/khurana/public/test.root"]

def readfile(inputfile):
    file_=uproot4.open(inputfile)
    print ("file opened")
    tree_ = file_["outTree"].arrays()
    print ("number of events: ", len(tree_))
```

Now if I call this using 
```
readfile(file_[0])
``` 

it works fine, 

however when tried to use the multiprocessing: 

iterable = file_                                                                                                                                                                                            
pool = mp.Pool(2)                                                                                                                                                                                           
func = partial(readfile)                                                                                                                                                                                    
pool.map(func, iterable)                                                                                                                                                                                    
pool.close()                                                                                                                                                                                                
pool.join()                                                                                                                                                                                                 


it is stuck forever, 

Do you have any clue what can be a reason for this, or you see something missing in the snippet. I wonder this was working fine for another version of code in uproot3. 

Thanks.

**Comment by jpivarski** [comment]
"Stuck forever" is a symptom of an error in Uproot 4 that has no equivalent in Uproot 3, so that's a hint for me.

(Namely, Uproot 4 bundles byte intervals to read from a file into a single request and interprets them as they come in on a `queue.Queue`. If the number of file chunks that show up on this queue is less than the expected number, it's going to keep waiting for them to appear. Uproot 3 has no equivalent because it used a less efficient fetch-on-demand method. In your case, it looks like I got the expected number of chunks wrong, so I'll start by reproducing your example. Thanks!)

**Comment by ramankhurana** [comment]
Thanks for adding to the list, just a followup, can this be a reason for being stuck forever on an root file with a empty tree. The tree has the same structure as others, just that entries are zero so none of the  branch has any information.

**Comment by jpivarski** [comment]
I'll check that case, too.

**Comment by ramankhurana** [comment]
Thanks Jim, btw is there a possibly some other option already in uproot4 while can allow parallel processing?

**Comment by jpivarski** [comment]
All of the array-fetching functions (such as [HasBranches.arrays](https://uproot4.readthedocs.io/en/latest/uproot4.behaviors.TBranch.HasBranches.html#arrays)) have `decompression_executor` and `interpretation_executor` parameters, which take Python 3 executors. You don't want to make these process pools, because you don't want to be sending data between processes, but thread pools would make sense. The default `decompression_executor` has as many workers as the number of cores, but the default `interpretation_executor` is a trivial executor (no parallel processing). That's because decompression algorithms release the GIL and are good to parallelize, but interpretation is usually just casting with NumPy, which is not an expensive operation. However, there are cases in which interpretation is expensive Python code, though there's still not a lot of advantage because Python doesn't release the GIL.

**Comment by jpivarski** [comment]
In fact, that's what's causing all the trouble: the default `uproot4.decompression_executor` and `uproot4.interpretation_executor` are global, and multiprocessing is trying to send this immobile objects to the other process.

**Comment by jpivarski** [comment]
So now I've removed the global default Executors; opened files and functions like `uproot4.iterate` and `uproot4.concatenate` now take `decompression_executor` and `interpretation_executor` arguments, like the other array-fetching functions. The problem was that multiprocessing tried to move these objects between processes, which cannot possibly work (because threads are bound to a process). Instead of raising some sort of error, Python froze.

This is different from the freezing that I was expecting, although attempting to read an empty file resulted in the more conventional type of freeze. Thanks for the tip: [I'm now testing for that](https://github.com/scikit-hep/scikit-hep-testdata/commit/1fe8cdcfda881385c1296ec3e5f7a04e274c2cb4).
