### ISSUE TITLE
Invalid file paths do not raise Exceptions

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/uproot4#182]
Hi @team,

Thanks for all the hard work here.

I noticed when calling `iterate` with an invalid file path, it silently failed rather than raising an exception.

From looking at the source code, it seems that it's likely due to this glob
https://github.com/scikit-hep/uproot4/blob/b5c0c5e0ec282660b7303fcf5019214270da8693/uproot4/behaviors/TBranch.py#L2796-L2799

I am not sure of the best solution. A first pass would be to raise a `FileNotFound` error if the string does not contain a glob pattern. Thereafter, however, do you want to treat non-matching globs as valid? Perhaps raising an exception if the globbing routine does not match any files across all patterns (rather than if any glob pattern fails)?

**Comment by jpivarski** [comment]
Maybe if any string is not a glob, it should raise a FileNotFoundException when it doesn't match. This is already true of remote URLs (which don't support glob-matching).

**Comment by agoose77** [comment]
> Maybe if any string is not a glob, it should raise a FileNotFoundException when it doesn't match. This is already true of remote URLs (which don't support glob-matching).

Sounds good to me, I'll take a look if you don't get manage round to it :)

**Comment by jpivarski** [comment]
I'll do it because I know the spot where this should go, but I'll let you test the proposed solution, to be sure that it has the properties you want. I think it's supposed to be:

   * any local filename (non-URL, except `"file://"`) with _no wildcard characters_ (`*`, `?`, `[`, `]`, `{`, `}`) must match an existent file or raise an error;
   * any local filename with wildcard characters is allowed to match nothing.

The second rule is important for describing sets of directories where files might exist, according to a naming convention, but it's allowed for some directories to be empty. (That's a situation I think comes up a lot.)
