### ISSUE TITLE
Lengths of TTrees/TBranchElements

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/uproot4#191]
This is just a minor thing, so set this to the lowest priority please ;)

In uproot4, the length is now returning the number of subbranches, while in uproot3 it was the number of "items" (number of entries from `fBasketEntry`), basically the array lengths of the subbranches, so to say. In my uproot3 based libraries I was relying on `len(f["path"])` to reflect the number of entries and used that to iterate over a branch. For `uproot4`, the public `.num_entries` attribute can be used, which is of course fine.

I already added that to the [wiki](https://github.com/scikit-hep/uproot4/wiki#length-of-ttreetbranchelements), but I wanted to quickly ask about the intention behind it.

I guess the main idea was to be more close to the `dict` interface since the `ROOTDirectory` class behaves like such, where `len()` also returns the number of keys. I am not sure if this is really the most common use-case in the uproot-context but it's of course not a big deal.
Anyways, the only thing I find a bit confusing though is the fact that `len()` does not count nested entries whereas `keys()` lists them, so `len(branch) != len(branch.keys())`, as seen in the example below. So I am wondering if `keys()` should only show the first level entries, to be conform to the `dict()` interface.

Let me quickly copy the example from the Wiki here just for the sake of completeness (and in case the Wiki is later emptied after the possible doc-migration):

```python
from skhep_testdata import data_path

import uproot as uproot3
import uproot4

branch = "E/Evt"

f3 = uproot3.open(data_path("uproot-issue431b.root"))
f3[branch]
# <TBranchElement b'Evt' at 0x00010f15f5e0>
len(f3[branch])
# 10
f3[branch]["id"].array()
# array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int32)


f4 = uproot4.open(data_path("uproot-issue431b.root"))
f4[branch]
# <TBranchElement 'Evt' (22 subbranches) at 0x00010f37a2b0>

len(f4[branch])
# 22

len(f4[branch].keys())  # note that this will also count nested entries
# 118

f4[branch].keys()
# ['AAObject', 'AAObject/TObject', 'AAObject/TObject/fUniqueID', ...,
#  'mc_trks/mc_trks.hit_ids', 'mc_trks/mc_trks.error_matrix', ...]

len([k for k in f4[branch].keys() if "/" not in k])  # only top-level subbranches
# 22

f4[branch].num_entries
# 10
```

**Comment by jpivarski** [comment]
The `__len__` method is part of the [Mapping protocol](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes), and although I don't see it written down anywhere, I think the implication is that `__len__` must be the number of items that `__iter__` would yield. I struggled with that in Uproot 3, but TTree in Uproot 3 didn't officially support the Mapping protocol. (It just duck-typed relatively well.)

You're right that ReadOnlyDirectory has more reason to be a Mapping than HasBranches, but these two things are more fully integrated now—you can "getitem" through directories into branches, a feature that partially worked by accident in Uproot 3, which I found out about because people used it in their examples. (That's clearly a desire path. And [explicitly requested](https://github.com/scikit-hep/uproot/issues/444) and [user-contributed](https://github.com/scikit-hep/uproot/pull/459).) For example, we can treat branches and subbranches as though they were directories in a single string with slashes:

```python
>>> import uproot4
>>> import skhep_testdata
>>> f = uproot4.open(skhep_testdata.data_path("uproot-nesteddirs.root"))

>>> f.keys()
['one;1', 'one/two;1', 'one/two/tree;1', 'one/tree;1', 'three;1', 'three/tree;1']

>>> f["one/two/tree"].keys()
['Int32', 'Int64', 'UInt32', 'UInt64', 'Float32', 'Float64', 'Str', 'ArrayInt32', 'ArrayInt64', 'ArrayUInt32',
 'ArrayUInt64', 'ArrayFloat32', 'ArrayFloat64', 'N', 'SliceInt32', 'SliceInt64', 'SliceUInt32', 'SliceUInt64',
 'SliceFloat32', 'SliceFloat64']

>>> f["one/two/tree/Int32"]
<TBranch 'Int32' at 0x7fa5792740a0>
```

Having both of these things, which are treated equivalently, both satisfy the Mapping protocol removes the friction I'd expect if one were a Mapping and the other were not. That's also why we don't have "TTree" behavior, we have "HasBranches" behavior, because a TTree with branches can be treated the same way as a branch with subbranches.

Now, it is a pain point that `len(ttree)` returns the number of branches, rather than the number of entries. Without any of the motivations described above, I'd expect `len(ttree)` to be the number of entries (which is, I guess, why that was the case in Uproot 3). But if so, then what's `__iter__`? I think I made `__iter__` raise an exception in Uproot 3 because I know what users might be thinking, and it's not that.

We can see some of this cognitive dissonance here:

```python
>>> events = uproot4.open(skhep_testdata.data_path("uproot-Zmumu.root"))["events"]

>>> len(events)
20
>>> events.num_entries
2304

>>> for branch in events:
...     print(branch)
... 
<TBranch 'Type' at 0x7fa5791ac4c0>
<TBranch 'Run' at 0x7fa5791acc10>
<TBranch 'Event' at 0x7fa5791b0370>
<TBranch 'E1' at 0x7fa5791b0a90>
<TBranch 'px1' at 0x7fa5791b0f40>
<TBranch 'py1' at 0x7fa5791b6910>
<TBranch 'pz1' at 0x7fa5791b6dc0>
<TBranch 'pt1' at 0x7fa5791bc790>
<TBranch 'eta1' at 0x7fa5791bceb0>
<TBranch 'phi1' at 0x7fa5791c2610>
<TBranch 'Q1' at 0x7fa5791c2d30>
<TBranch 'E2' at 0x7fa5791c9490>
<TBranch 'px2' at 0x7fa5791c9bb0>
<TBranch 'py2' at 0x7fa5791ce310>
<TBranch 'pz2' at 0x7fa5791cea30>
<TBranch 'pt2' at 0x7fa5791ceee0>
<TBranch 'eta2' at 0x7fa5791d48b0>
<TBranch 'phi2' at 0x7fa5791d4fd0>
<TBranch 'Q2' at 0x7fa5791d9730>
<TBranch 'M' at 0x7fa5791d9e50>

>>> for event in events.arrays():
...     print(repr(event))
... 
<Record ... phi2: -0.441, Q2: -1, M: 82.5} type='{"Type": string, "Run": int32, ...'>
<Record ... phi2: 2.74, Q2: 1, M: 83.6} type='{"Type": string, "Run": int32, "Ev...'>
<Record ... phi2: 2.74, Q2: 1, M: 83.3} type='{"Type": string, "Run": int32, "Ev...'>
<Record ... phi2: 2.74, Q2: 1, M: 82.1} type='{"Type": string, "Run": int32, "Ev...'>
<Record ... phi2: -2.71, Q2: -1, M: 90.5} type='{"Type": string, "Run": int32, "...'>
<Record ... phi2: 0.583, Q2: 1, M: 89.8} type='{"Type": string, "Run": int32, "E...'>
...
```

If we make `len(ttree)` be `ttree.num_entries`, then we should also make `iter(ttree)` be `iter(ttree.arrays())`, though I would not recommend the latter for performance—I certainly wouldn't want to make it easy or suggest that it's the right way to go by making it `__iter__`.

So what do we do if one motivation (slicing through directories) implies one design and another motivation (Pythonic length/iteration) implies another? In this case, Pythonic iteration is also something I'd recommend against, so that's why the first motivation won.

(Incidentally, in Julia, there would be nothing wrong with naive iteration over such an object. Some physical properties of the implementation—like the performance of Python—have interface consequences.)

**Comment by tamasgal** [comment]
OK, thanks for the detailed clarification, as always, it makes of course sense. I also agree with your last comment about performance subtleties dictating interface design.

Let's close this then. I will put a link to this issue into the wiki!
