### ISSUE TITLE
TH1 raises `kind` instead of returning

### ISSUE THREAD

**Issue by beojan** [scikit-hep/uproot4#235]
On line 108 of `TH1.py`, `kind` raises `COUNT` instead of returning it, leading to the error:
```
----> 1 hasattr(a, 'kind')

/usr/lib/python3.9/site-packages/uproot/behaviors/TH1.py in kind(self)
    106         ``"MEAN"`` for profile plots (TProfile*).
    107         """
--> 108         raise "COUNT"
    109
    110     def values(self, flow=False):

TypeError: exceptions must derive from BaseException
```

**Comment by jpivarski** [comment]
Thanks @beojan and @henryiii! That's a bizarre mistake. I'll merge the PR as soon as the tests pass.

**Comment by henryiii** [comment]
My standard reminder: MyPy catches things like this. ;)

**Comment by jpivarski** [comment]
Now I see how that happened. Most of the other methods on the abstract class `raise NotImplementedError`, but this one should return a value. Or, as in @henryiii's fix, it now raises NotImplementedError on the abstract class but returns `"COUNT"` for each concrete class. That's less prone to error (e.g. if a new concrete class is ever added, though that's unlikely since a new `TH1` descendent would have to be added to ROOT, and any new histogram types in ROOT will likely be in the ROOT 7 class hierarchy).
