### ISSUE TITLE
Unable to read arrays onto GPU with cupy

### ISSUE THREAD

**Issue by asnaylor** [scikit-hep/uproot4#242]
I'm trying to read root data onto an Nvidia GPU with uproot and cupy. I can read the data fine onto cpu but when i set the `library='cp'` I get `ValueError: non-scalar numpy.ndarray cannot be used for fill`.

I've posted the code I used below (I'm also using publicly available data: `root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root` so anyone can try to replicate the error):
```python
Python 3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import awkward as ak
>>> ak.__version__
'1.0.1'
>>> import uproot
>>> uproot.__version__
'4.0.0'
>>> import cupy as cp
>>> cp.__version__
'8.3.0'
>>> tree = uproot.open('root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root')['Events']
>>> cpu_array = tree.arrays(['nElectron'])
>>> cpu_array
<Array [{nElectron: 0}, ... {nElectron: 1}] type='29308627 * {"nElectron": uint32}'>
>>>
>>> gpu_array = tree.arrays(['nElectron'], library='cp')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/envs/ml_pos_reco/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 1111, in arrays
    _ranges_or_baskets_to_arrays(
  File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/envs/ml_pos_reco/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3430, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/envs/ml_pos_reco/lib/python3.8/site-packages/uproot/source/futures.py", line 46, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/envs/ml_pos_reco/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3401, in basket_to_array
    arrays[branch.cache_key] = interpretation.final_array(
  File "/home/anaylor/.pyenv/versions/miniconda3-4.3.30/envs/ml_pos_reco/lib/python3.8/site-packages/uproot/interpretation/numerical.py", line 89, in final_array
    output[: stop - entry_start] = basket_array[local_start:local_stop]
  File "cupy/core/core.pyx", line 1299, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/_routines_indexing.pyx", line 52, in cupy.core._routines_indexing._ndarray_setitem
  File "cupy/core/_routines_indexing.pyx", line 884, in cupy.core._routines_indexing._scatter_op
  File "cupy/core/core.pyx", line 542, in cupy.core.core.ndarray.fill
ValueError: non-scalar numpy.ndarray cannot be used for fill
```

**Comment by jpivarski** [comment]
Thanks for pointing this out—the `library="cp"` interface has not been consistently tested, as it can't be included in CI that runs on machines without GPUs. I'll take this as a note to give the `library="cp"` interface more attention (or remove it if I'm unable to do so).

That bug looks like an easy one to fix: it looks like a NumPy array is being assigned into a CuPy array. I doubt it's related to the specific file that you're using, but thanks for including it in case it is. Uproot's `library="cp"` interface is limited to simple data types (rectilinear arrays of numbers) because that's what CuPy supports. Thus, there aren't very many types to test. (For more complex data on GPUs, Awkward Array's GPU support is coming along...)

If you need a way to get this to work, you can definitely use `library="np"` and then transfer the data to CuPy in a subsequent step. The data begin life in main memory, so there's always going to be _some_ transfer from main memory to the GPU, whether that happens inside of Uproot or in your code, one step afterward. There isn't a major performance benefit to having that step be in Uproot, maybe just the fact that copying from individual TBasket arrays into a single output array can also be the copy from main memory to GPU. There might also be a convenience to getting a dict of CuPy arrays without having to iterate that dict to copy them yourself. Okay, that's sounding like reason enough to not just remove the `library="cp"` option.

(The `library="cp"` option was originally added to convince myself of the generality of this `library` argument as a concept.)

**Comment by asnaylor** [comment]
Thanks for the quick response. That's cool that Awkward Array GPU support is coming, that will be very helpful as some of the data I use is jagged so requires Awkward arrays anyways. 

Should I just close this issue as Awkward Array GPU support is coming and that's more likely to be preferred than cupy?

**Comment by jpivarski** [comment]
No, there's still a real bug here: this issue is a reminder to do something about it. I either have to fix it or remove the `library="cp"` support. Maintenance of this feature will be difficult if it can't be tested regularly in CI. I'll have to think about that.

**Comment by jpivarski** [comment]
As you can see in #279, I've decided to remove CuPy support. It wouldn't have been a huge performance advantage to copy the data to the GPU in the TBasket-to-concatenated-array stage, rather than one step later in your own code (i.e. you read the array into main memory and then copy it to the GPU yourself). Without a way to regularly test it in CI, we can't say that we really "supported" the feature, anyway. At least now we're not leading you on.
