### ISSUE TITLE
Thoughts about porting Uproot3 writing to Uproot4

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/uproot4#25]
This will take some thought, and it will come after the two reading projects.

For now, though, I should bring this to @reikdas's attention.

**Comment by reikdas** [comment]
One of the design decisions in uproot 3's writing code that seemed wrong in hindsight was using high level functions to dictate the serialization for objects that uproot claims to be able to write instead of using separate classes with their own write methods. 

For eg - 
We have a `put_tleaf` function like here - https://github.com/scikit-hep/uproot/blob/master/uproot/write/objects/TTree.py#L588 instead of having a TLeaf class with its own write method. 

One of the negative side effect of having done this was that we had to use hacky methods to handle TObjArrays where we had to pass the classnames as strings and have special conditions to handle different objects in the logic for TObjArray - https://github.com/scikit-hep/uproot/blob/master/uproot/write/objects/util.py#L33.

**Comment by nsmith-** [comment]
Is there a chance that simpler object writing like TH1* could be supported in short term, or is the overall design not yet finalized to be able to implement it?

**Comment by jpivarski** [comment]
The structure for writing anything is not yet started. See the [Write methods](https://github.com/scikit-hep/uproot4/projects/3#card-40292604) project.

**Comment by goi42** [comment]
Just to say, now that **uproot3** _and_ [**root_pandas**](https://github.com/scikit-hep/root_pandas) have both been deprecated, I am unaware of any currently supported project that allows for writing pandas DataFrames to ROOT TTrees; to my knowledge, the [Write methods](https://github.com/scikit-hep/uproot4/projects/3#card-40292604) project is the only existing effort that might solve this.

**Comment by jpivarski** [comment]
I didn't mention it here, but I'm scheduled to work on Uproot 4 writing in April. (March is [Vector](https://github.com/scikit-hep/vector), April is Uproot-writing.)

But on the point of turning Pandas DataFrames into ROOT files, we're also missing an `ak.from_pandas` to reverse [ak.to_pandas](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_pandas.html). It's not hard to turn a Pandas DataFrame with a simple index into equivalent Awkward Arrays and therefore ROOT files, but if the DataFrame has a MultiIndex, I think you'd want that to be turned into a jagged array (reversing what [ak.to_pandas](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_pandas.html) does), and therefore arrays-per-event in ROOT.

But I don't think that root_pandas did the MultiIndex → jagged ROOT, either, so maybe I'm thinking about more complex use-cases than people have.

**Comment by eduardo-rodrigues** [comment]
Comment following from https://github.com/scikit-hep/root_pandas/commit/5b174a4bb119573bd120c04a636db9e2d9aca874#commitcomment-48451554.

**Comment by goi42** [comment]
@jpivarski Thanks for the update. This is certainly a more complicated use-case than I have at the moment, but obviously I cannot speak for the broader community. 

If it is easier to support the simple case while development for the complicated case is ongoing, I would certainly appreciate an earlier release, though for now I can continue with the deprecated **root_pandas**.

**Comment by eduardo-rodrigues** [comment]
Hi @goi42, on these matters - yes root_pandas is deprecated for good reasons. But point is taken that coverage in replacement is not 100% yet. This and many other packages really are community efforts and you should feel free and urged to help out, especially when you are a user. In short, if you have been a user of root_pandas for a while, would you consider patching root_pandas e.g. for a more recent ROOT or Python version? From what I've seen in messages every now and then, there are various colleagues out there that would be keen on that. Maybe that's not much work to you? Thanks.

**Comment by chrisburr** [comment]
> would you consider patching root_pandas 

The real problem here is `root_numpy` and it's test suite has been failing since ROOT 6.16.00 was released. If someone is willing to revive `root_numpy` then the continued maintenance of `root_pandas` is relatively simple.

**Comment by eduardo-rodrigues** [comment]
BTW @goi42, if you got out of ROOT with root_pandas, what is your use-case "for writing pandas DataFrames to ROOT TTrees" back again? It is useful to know to better understand the needs out there :-).

**Comment by eduardo-rodrigues** [comment]
> > would you consider patching root_pandas
> 
> The real problem here is `root_numpy` and it's test suite has been failing since ROOT 6.16.00 was released. If someone is willing to revive `root_numpy` then the continued maintenance of `root_pandas` is relatively simple.

Totally, @chrisburr. I'm aware of that. My general comment on maintenance of community packages still holds :-).

**Comment by goi42** [comment]
@eduardo-rodrigues `root_pandas` allowed me to do some pythonic calculations and write out a friend `TTree` with the results, which I could then use for histogramming, etc., within `ROOT`. 

As I mentioned in the other comment you linked above, I may find time to contribute to the improvement of these features in the future; part of community development is drawing attention to use-cases and finding out what other work is being done.

**Comment by jpivarski** [comment]
Writing arbitrarily complex `TTrees` would have open-ended difficulty*, so assigning a friend should be easier than that. I don't see how there's an equivalence between these two problems, but I can look into how to assign friend relationships, likely after all other work (including jagged arrays in `TTrees`) is done.

*If the space of types were enumerable, like "primitive, list, union, record, and all combinations thereof," then this would be a finite problem: implement the generators of the space and test them in combinations, at least two deep. But the kinds of objects that can go into `TTrees` are "all C++ types," a space with a lot of generators and new ones being added with each new standard. Such a problem would involve understanding how ROOT encodes them (and ROOT doesn't include all C++ types, either—there are a few recent ones that are still pending) and how to represent them as Python data. RNTuple is simplifying this considerably by defining a suite of language-independent types (e.g. "primitive, list, union, record") at one layer, and then describing C++ types at a layer above that. We would target the language-independent types and leave it to ROOT to interpret them as C++ types in C++.

But yeah: friend `TTrees`, I'll look into that when the rest is done.

**Comment by dcervenkov** [comment]
Happy to hear that you'll look into it! And what you say about treating the language-independent types and leaving the C++ types up to ROOT sounds very reasonable. I didn't quite understand if this is on the roadmap or not.

Let me comment on how the two problems are connected. Our use-case is that a user supplies a ROOT file with a `TTree`. We run certain calculations and want to add the results of these calculations as branches to the user's `TTree`. Since the user `TTree` is out of our control (and can in principle be quite complicated), writing the whole thing using Uproot seems unrealistic (and inefficient as most of the data is already on disk). What we can do using PyROOT is add a `TTree` with the new branches to the user file and make it a friend of the original `TTree`. This allows the user to work as if their `TTree` had all the branches.

**Comment by eduardo-rodrigues** [comment]
Just to add - this is related to official LHCb PID work for run 3 :-).

**Comment by nsmith-** [comment]
Is it a hard requirement to use ROOT file format to store the additional data? Because otherwise there are many options already available, e.g. saving the derived awkward arrays in [parquet](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_parquet.html) or even pickle and then open them and attach with the original tree using `ak.zip()`.

**Comment by jpivarski** [comment]
Although you're right that friend trees are the right solution here (less data to write), this particular problem could be solved without Uproot actually understanding the branches it's copying. Suppose, for the moment, that Uproot doesn't do friend trees, but you want to make a new TTree that's just like the old one with extra branches added. We could have functionality that copies all TStreamerInfo, the original TBranches with their hierarchical structure, and all their associated TBaskets (maybe without uncompressing them, just copying them as binary blobs, or with uncompressing and merging—understanding the data is not necessary for concatenation), and then also add the new TBranches. That would solve the problem, and maybe it would be good to have that functionality also: "blind copy."

With an uncompress-merge-recompress option, this could be useful for repartitioning data (independently of adding new TBranches), as there are a lot of cases with TBaskets or TFiles that are too small. The issues I described above, of needing Python types to mirror the C++ types and needing to know how each is serialized, don't apply to this case, since we can just take the raw byte stream as-is (and also not touch the hierarchical structure of the TBranches, since part of the type information is encoded in the nesting of TBranches within TBranches).

**Comment by dcervenkov** [comment]
@nsmith- Yes, this is the output of our tool - the end product that the users use. We can't ask them to deal with another file format.

@jpivarski That definitely sounds interesting and feasible as a solution to our problem.

**Comment by jpivarski** [comment]
See #321; this is done.  `:)`
