### ISSUE TITLE
Can't open THD1 histogram

### ISSUE THREAD

**Issue by guilindner** [scikit-hep/uproot4#250]
Hi,
Some histograms are not being opened using uproot.
The .root file is working on default root, rootbrowse and uproot3.

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/omitted/venv/lib/python3.9/site-packages/uproot/reading.py", line 1971, in __getitem__
    return self.key(where).get()
  File "/home/omitted/venv/lib/python3.9/site-packages/uproot/reading.py", line 2356, in get
    out = cls.read(chunk, cursor, context, self._file, selffile, parent)
  File "/home/omitted/venv/lib/python3.9/site-packages/uproot/model.py", line 1164, in read
    raise ValueError(
ValueError: Unknown version 1 for class TH1D that cannot be skipped because its number of bytes is unknown.
```

steps to reproduce
```python
>>> import uproot
>>> uproot.open("B4.root")['Eabs']
```

If you ignore the **raise ValueError** (line 1172 from model.py) and use **versioned_cls = cls.new_class(file, version)** the histogram works fine.

I'm attaching a root file from the Geant4 example case B4a (obtained running the run2.mac)
[B4.txt](https://github.com/scikit-hep/uproot4/files/5847269/B4.txt)

Thanks

**Comment by jpivarski** [comment]
It was a one-word fix! Uproot 3 automatically reads all streamers (instructions for how to deserialize the classes in a ROOT file) as soon as a file is opened, but Uproot 4 only reads streamers needed for the classes that are actually read. That's why it worked in Uproot 3.

For some reason, this object doesn't have a `num_bytes`. I don't know why that is, but it's not necessary to deserialize it. I think that "if" condition is supposed to be checking for the existence of a `version`, which _is_ necessary (unless we just guess that it's the maximum version in the streamers: there's rarely more than one of them).

```diff
--- a/uproot/model.py
+++ b/uproot/model.py
@@ -1160,11 +1161,12 @@ class DispatchByVersion(object):
         if versioned_cls is not None:
             pass
 
-        elif num_bytes is not None:
+        elif version is not None:
             versioned_cls = cls.new_class(file, version)
 
         elif context.get("in_TBranch", False):
             versioned_cls = cls.new_class(file, "max")
 
         else:
             raise ValueError(
```
