### ISSUE TITLE
Histogram protocol issue?

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#265]
I am confused about `PlottableAxisContinuous.__getitem__`: for uproot4 it seems to give the one-indexed values where I was expecting zero-indexed, since `__len__` gives the number of bins without flow. For example:
```
>>> h = uproot.open('https://raw.githubusercontent.com/CoffeaTeam/coffea/master/tests/samples/testSF2d.histo.root:scalefactors_Tight_Electron')
>>> axis = h.axes[0]
>>> len(axis)
10
>>> axis.edges()
array([-2.5  , -2.   , -1.566, -1.444, -0.8  ,  0.   ,  0.8  ,  1.444,
        1.566,  2.   ,  2.5  ])
>>> axis.edges().shape
(11,)
>>> axis[0]
(-2.0, -1.566)
```

**Comment by jpivarski** [comment]
After much back-and-forth, the histogram protocol settled on not including under/overflow bins, and _going beyond_ the protocol, we are allowed to include a `flow=True/False` option to turn it on and off. See, for instance, [TH1.values](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TH1.TH1.html#values) and [TH1.edges](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TAxis.TAxis.html#edges).

But I think what you're running up against is not under/overflow bin handling, but the [fencepost principle](https://en.wikipedia.org/wiki/Off-by-one_error#Fencepost_error). If you do `__getitem__`, you get a section of the fence defined by the two posts that border it. If you do `edges()`, you see all the posts. It's like the difference between `offsets` and `starts/stops`.

If anything, this should be categorized as "policy," rather than a "bug," but I really don't want to revisit the histogram protocol definitions again. I'd like to let those dogs lie.

**Comment by nsmith-** [comment]
Uh.. I am fine with fenceposts or whatever but why don't I get the first (not overflow) bin `(-2.5, -2)` when I ask for bin index 0?

**Comment by jpivarski** [comment]
Oh, that is strange, now that I look at the actual numbers. This `edges` doesn't look consistent with the `__getitem__`. If you had asked for `flow=True`, it would add infinity fenceposts to the ends:

https://github.com/scikit-hep/uproot4/blob/ea0456cd4d101eed8c8e20207560e6057bf063c3/uproot/behaviors/TAxis.py#L215-L223

So that means that the `__getitem__` should return `fXbins[where], fXbins[where + 1]` instead of

https://github.com/scikit-hep/uproot4/blob/ea0456cd4d101eed8c8e20207560e6057bf063c3/uproot/behaviors/TAxis.py#L61-L75

which, I guess, only affects irregularly spacaed bins. This is looking more like a bug to me, too (and not a histogram protocol thing).

**Comment by jpivarski** [comment]
I've checked and we just don't have any test files with histograms containing irregularly spaced bins. The fact that we have to find files to do proper tests is part of a larger problem: scikit-hep/uproot4#269 and scikit-hep/uproot4#240.

It looks to me like replacing

https://github.com/scikit-hep/uproot4/blob/bfc1380ca304c5b0108417954946b1d793cfeed6/uproot/behaviors/TAxis.py#L74-L75

with

https://github.com/scikit-hep/uproot4/blob/714f86309059d708c180956cd14f1acf6849052d/uproot/behaviors/TAxis.py#L74-L75

is all we have to do. The `TAxis.__getitem__` has to be coordinated with `TAxis.intervals` (same file), but that looks correct.
