### ISSUE TITLE
Xrootd vector read has no timeout

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/uproot4#292]
In https://github.com/scikit-hep/uproot4/blob/7e3353cfdec91c340c7a0e26a31a695d2db3bcf1/uproot/source/xrootd.py#L341-L343 there is no timeout argument passed to `vector_read`. The signature supports it: https://xrootd.slac.stanford.edu/doc/python/xrootd-python/modules/client/file.html#XRootD.client.File.vector_read and the regular read does use it:
https://github.com/scikit-hep/uproot4/blob/7e3353cfdec91c340c7a0e26a31a695d2db3bcf1/uproot/source/xrootd.py#L152-L154

**Comment by jpivarski** [comment]
Since `self` in the first code block is a XRootDSource, which has a `self._timeout`, is there any downside to calling the equivalent of `_xrd_timeout` and passing it to `vector_read`? 

`_xrd_timeout` is unfortunately not defined for XRootDSource, but XRootDResource, though it could become a free function:

https://github.com/scikit-hep/uproot4/blob/7e3353cfdec91c340c7a0e26a31a695d2db3bcf1/uproot/source/xrootd.py#L90-L94

**Comment by nsmith-** [comment]
I think it should be as simple as adding `timeout=self._resource._xrd_timeout()` to the call. I'll make a PR soon

**Comment by jpivarski** [comment]
If the resource has the same `_timeout` (i.e. the data is simply copied). I would think that it is.

**Comment by nsmith-** [comment]
The answer to your last question is yes it does just copy the timeout currently.
