### ISSUE TITLE
Network access sources leak threads (and maybe also memory)

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/uproot4#333]
In different tests that run over multiple files, using both xrootd and http access sources i'm seeing an increase in the number of threads. Also it seems sometimes (in http and also in xrootd even after the fix from https://github.com/xrootd/xrootd/pull/1440) there might be a slight memory leak. On the one hand, vmem increases proportional to the increasing number of threads (don't know if that means anything). But on the other hand i also sometimes see an increase of RSS/PSS memory.

One reproducer i could come up with is the following script:

```python
#!/usr/bin/env python

import os
import uproot

base_url = "https://atlas-opendata.web.cern.ch/atlas-opendata/samples/2020/4lep/MC/"

filenames = [
    "mc_364100.Zmumu_PTV0_70_CVetoBVeto.4lep.root",
    "mc_364101.Zmumu_PTV0_70_CFilterBVeto.4lep.root",
    "mc_364102.Zmumu_PTV0_70_BFilter.4lep.root",
    "mc_364103.Zmumu_PTV70_140_CVetoBVeto.4lep.root",
    "mc_364104.Zmumu_PTV70_140_CFilterBVeto.4lep.root",
    "mc_364105.Zmumu_PTV70_140_BFilter.4lep.root",
    "mc_364106.Zmumu_PTV140_280_CVetoBVeto.4lep.root",
    "mc_364107.Zmumu_PTV140_280_CFilterBVeto.4lep.root",
    "mc_364108.Zmumu_PTV140_280_BFilter.4lep.root",
    "mc_364109.Zmumu_PTV280_500_CVetoBVeto.4lep.root",
    "mc_364110.Zmumu_PTV280_500_CFilterBVeto.4lep.root",
    "mc_364111.Zmumu_PTV280_500_BFilter.4lep.root",
    "mc_364112.Zmumu_PTV500_1000.4lep.root",
    "mc_364113.Zmumu_PTV1000_E_CMS.4lep.root",
    "mc_364114.Zee_PTV0_70_CVetoBVeto.4lep.root",
    "mc_364115.Zee_PTV0_70_CFilterBVeto.4lep.root",
    "mc_364116.Zee_PTV0_70_BFilter.4lep.root",
    "mc_364117.Zee_PTV70_140_CVetoBVeto.4lep.root",
    "mc_364118.Zee_PTV70_140_CFilterBVeto.4lep.root",
    "mc_364119.Zee_PTV70_140_BFilter.4lep.root",
    "mc_364120.Zee_PTV140_280_CVetoBVeto.4lep.root",
    "mc_364121.Zee_PTV140_280_CFilterBVeto.4lep.root",
    "mc_364122.Zee_PTV140_280_BFilter.4lep.root",
    "mc_364123.Zee_PTV280_500_CVetoBVeto.4lep.root",
    "mc_364124.Zee_PTV280_500_CFilterBVeto.4lep.root",
    "mc_364125.Zee_PTV280_500_BFilter.4lep.root",
    "mc_364126.Zee_PTV500_1000.4lep.root",
    "mc_364127.Zee_PTV1000_E_CMS.4lep.root",
    "mc_364128.Ztautau_PTV0_70_CVetoBVeto.4lep.root",
    "mc_364129.Ztautau_PTV0_70_CFilterBVeto.4lep.root",
    "mc_364130.Ztautau_PTV0_70_BFilter.4lep.root",
    "mc_364131.Ztautau_PTV70_140_CVetoBVeto.4lep.root",
    "mc_364132.Ztautau_PTV70_140_CFilterBVeto.4lep.root",
    "mc_364133.Ztautau_PTV70_140_BFilter.4lep.root",
    "mc_364134.Ztautau_PTV140_280_CVetoBVeto.4lep.root",
    "mc_364135.Ztautau_PTV140_280_CFilterBVeto.4lep.root",
    "mc_364136.Ztautau_PTV140_280_BFilter.4lep.root",
    "mc_364137.Ztautau_PTV280_500_CVetoBVeto.4lep.root",
    "mc_364138.Ztautau_PTV280_500_CFilterBVeto.4lep.root",
    "mc_364139.Ztautau_PTV280_500_BFilter.4lep.root",
    "mc_364140.Ztautau_PTV500_1000.4lep.root",
]

import gc

for filename in filenames:
    with uproot.open(f"{os.path.join(base_url, filename)}:mini") as tree:
        print(tree.arrays(filter_name="lep_*"))
    gc.collect()
```

When i run this through [prmon](https://github.com/HSF/prmon) with 

```
prmon --interval 1 -- python test_uproot_http.py
```

i get this graph for the number of threads:

```
prmon_plot.py --input prmon.txt --xvar wtime --yvar nthreads
```

![image](https://user-images.githubusercontent.com/3707225/115054287-5cb28b80-9ee0-11eb-89e3-a46a04699994.png)

and this for RSS and PSS

```
prmon_plot.py --input prmon.txt --xvar wtime --yvar pss,rss --yunit GB
```

![image](https://user-images.githubusercontent.com/3707225/115054571-a7340800-9ee0-11eb-9316-ff169d64d60e.png)

For now i don't have a reproducer for xrootd, but i think one can see similar issues there (i'll try to come up with an example).

**Comment by nikoladze** [comment]
```python
>>> import uproot
>>> uproot.__version__
'4.0.7'
```

**Comment by jpivarski** [comment]
This wouldn't happen with XRootD because it was leaking through the HTTP fallback mechanism: a lot of servers HTTP servers don't support multi-part GET, so the optimistic default of asking for all TBaskets in one request has to fallback to one TBasket per request with `num_fallback_workers` threads (10) to collect the TBaskets as the server provides them.

I looked up prmon, decided that I didn't want to custom-install something (no conda), and checked the thread count with print statements. I'm going to try to find some way to quantify the memory usage, since that's something psutil ought to be able to do. I suspect, though, that the memory leak was due to the thread leak: there were Python objects (instances of a ResourceWorker class and possibly open HTTP connections) attached to each thread.

**Comment by jpivarski** [comment]
Nevermind: prmon [does have a conda installer](https://anaconda.org/conda-forge/prmon).

**Comment by jpivarski** [comment]
First, the number of threads now:

![PrMon_wtime_vs_nthreads](https://user-images.githubusercontent.com/1852447/115061333-af734f80-9eae-11eb-93f8-d721e984e1f1.png)

There was a lucky/unlucky moment when the interval of sampling happened to be during a time when the fallback threads were active. 12 = 2 (main and HTTPSource thread) + 10 (fallback worker threads).

**Comment by jpivarski** [comment]
This is from another run because I didn't realize that the same temporary files would be used for memory profiling, too, before I deleted them. The new number of threads is a flat line at 2 and the memory usage is:

![PrMon_wtime_vs_pss_rss](https://user-images.githubusercontent.com/1852447/115061995-738cba00-9eaf-11eb-9e70-cc3eca364da7.png)
