### ISSUE TITLE
lazy not working as documented

### ISSUE THREAD

**Issue by peguerosdc** [scikit-hep/uproot4#360]
On the ["Reading on demand with lazy arrays"](https://uproot.readthedocs.io/en/latest/basic.html#reading-on-demand-with-lazy-arrays) site, there are two apparent ways of using `lazy`:

# events.lazy

The first code snippet says that a file can be lazy-loaded using:
````python
array = events.lazy(["dir1/*.root:events", "dir2/*.root:events"])
````
and array should be of type `<Array>`, but it doesn't say what `events` is. I guess that section is assuming the reader has gone through all the previous sections and he knows that it is defined (under ["Finding objects in a file"](https://uproot.readthedocs.io/en/latest/basic.html#finding-objects-in-a-file) ) as:

````python
events = uproot.open("https://scikit-hep.org/uproot3/examples/Zmumu.root:events")
````
so `events` is of type `<TTree 'events' (20 branches) at 0x78e575394b20>`. I tried that approach with my own root file and it didn't work:

````python
events = uproot.open("./radospet_1April21_taupair_b1s0_clean.root:tau3x1")
print(events.lazy)
"""
AttributeError: 'Model_TTree_v20' object has no attribute 'lazy'
"""
````
I guess that's what I was expecting as it wouldn't make sense to use a `TTree` to open a file, but well, that's what the docs say. Then I tried the second approach described later in that same section:

# uproot.lazy
Now this makes sense as I want to use the module `uproot` to lazy-open a file! The file seems to load correctly, but my array doesn't have the `cache` attribute:

````python
f = uproot.lazy("./radospet_1April21_taupair_b1s0_clean.root:tau3x1", step_size=100)
print(f.cache)
"""
AttributeError: no field named 'cache'
"""
````
And basically that's all the docs say about `lazy`, so I have no idea how to use it or if I should trust the rest of the document.

I would like to suggest adding full examples to the repository (and/or the docs) and running them as part of the unit tests to make sure everything is working as expected.

I am using uproot 4.0.7.

**Comment by jpivarski** [comment]
You're right: these are definitely errors in the documentation. There never was a `TTree.lazy`; I'm sorry for the confusion that typo caused. These examples were copy-pasted from tests performed while writing the tutorial—I don't know how that got garbled.

The other case of Awkward Arrays not having a `cache` property is a change in the Awkward Array library (not Uproot). Awkward Arrays are trees that can, in principle, include VirtualArrays with different caches, so there isn't a single cache to expose as a parameter. The example could be changed to access `_caches` (plural, a tuple of length 1), but it's not good to promote the use of hidden (underscored) attributes. Instead, I changed the example to use an explicitly passed-in cache.

Everything is updated: https://uproot.readthedocs.io/en/latest/basic.html#reading-on-demand-with-lazy-arrays

I agree that having automated tests for the documentation would solve these problems. Since the reference documentation (such as the [uproot.lazy](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.lazy.html) page) is generated from docstrings and the signature of the function itself, they're up-to-date. Testing examples, whether in the tutorials or in the reference, is much harder. We're trying to do exactly that with the Awkward Array documentation—instead of Sphinx restructured text pages, they're all [Jupytext markdown](https://github.com/scikit-hep/awkward-1.0/tree/main/docs-src), which means that the outputs are generated when the HTML is built, thereby testing them. Unfortunately, it doesn't actually stop the build if there are errors, so we've added [an explicit CI test](https://github.com/scikit-hep/awkward-1.0/blob/3b7009a23075a53f84cbe0333568325772d2fb95/.ci/azure-doctest-awkward.yml#L85-L93) to hunt for errors and stop a PR from being merged if it introduces an error. Nevertheless, there are still some kinds of errors that get through (pages missing from the table of contents, and therefore not included on the site), so that still needs to be improved.

Another issue with that is that the JupyterBooks that runs the Jupytext is separate from the Sphinx documentation that is generated from the docstrings and can be uploaded to ReadTheDocs, so Awkward Array has to have two documentation sites, one of which is hosted by Netlify. The examples in the reference documentation (docstrings) aren't tested, so it's still not a perfect sieve.

So I agree that it's desirable to have automated checks on documentation, but it will take some work to get that up and running.

On the other hand, thank you very much for reporting this! At least this error is now corrected.

@all-contributors please add @peguerosdc for tests

**Comment by peguerosdc** [comment]
awesome! I have checked the docs and indeed they are correct now, so I will close this issue as the error is fixed :smiley:
