### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect data check (too many root files at once?)

### ISSUE THREAD

**Issue by asnaylor** [scikit-hep/uproot4#370]
I'm using python concurrent futures (ProcessPoolExecutor) with uproot to fill boost histograms from many root files on one of the NERSC Cori supercomputer interactive haswell nodes (64 cores). The code i'm using run's 64 ProcessPoolExecutor workers and has worked fine running over 1000 root files (ranging from 0.5-3 GB's in size) but when i tried running it over 6000 root files I get a `zlib.error`. I thought maybe there was something up with the root file; checked the file which lead to this error and uproot opened it and pulled out the data fine. On re-running the code again over 6000 files again, this time a different file lead to the `zlib.error`. Is the error due to some i/o limitation, too many files at once?

I remove all the other code from my analysis function (did the test function below) and still got the `zlib.error`; the traceback says it's coming from trying to pull out the variables from the uproot tree.

Code snippet:
```python
def test_function(filename, tree_name):
  with uproot.open(filename) as f:
    variables = ['pulseArea_phd', 'triggerTimeStamp', 'triggerType']
    uproot_tree = f[tree_name]
    arrays = uproot_tree.arrays(variables)
```

Traceback:
```python
File "analysis_script.py", line 167, in test_function
    arrays = uproot_tree.arrays(variables)
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 1094, in arrays
    arrays, expression_context, branchid_interpretation = _regularize_expressions(
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3284, in _regularize_expressio
ns
    _regularize_expression(
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3133, in _regularize_expressio
n
    branch.interpretation,
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 2194, in interpretation
    self._interpretation = uproot.interpretation.identify.interpretation_of(
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/interpretation/identify.py", line 455, in interpretation_o
f
    if branch.streamer is not None:
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 2339, in streamer
    matches = self._file.streamers.get(fParentName)
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/reading.py", line 857, in streamers
    ) = streamer_key.get_uncompressed_chunk_cursor()
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/reading.py", line 2411, in get_uncompressed_chunk_cursor
    uncompressed_chunk = uproot.compression.decompress(
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/compression.py", line 280, in decompress
    uncompressed_bytestring = cls.decompress(data, block_uncompressed_bytes)
  File "/global/homes/a/asnaylor/.conda/envs/uproot-py38/lib/python3.8/site-packages/uproot/compression.py", line 105, in decompress
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect data check
```

Versions:
```python
uproot==4.0.7
python==3.8.8
```

**Comment by jpivarski** [comment]
Actually, on this, I'm stumped. If you're using a ProcessPool, then the Uproot instances are completely independent. (You're running Uproot _inside_ the ProcessPool, not passing ProcessPool as a `decompression_executor`, right? If you use a ProcessPool as a `decompression_executor`, then Uproot would need to copy compressed data to each process and copy uncompressed data back; probably not what you want, since it would be more efficient if they were completely independent. Still, it shouldn't break.)

Here's a question: does it always fail for the same file? In retrospect, I should have put a try-catch around `zlib.decompress(data)` to add a filename in case of failure: it's [src/uproot/compression.py#280](https://github.com/scikit-hep/uproot4/blob/efc6fd0ca773de30a524a081fff655414f09ee99/src/uproot/compression.py#L280) and you can get the filename from `chunk.source.file_path` if you want to try it. If it's always different files, then the data are being delivered to you in a non-deterministic way, which would most likely show up in a decompression checksum. (The largest blocks of data have to be decompressed, and any bit error would be caught by the checksum with high probability.)

If it's always the same file, then that's more perplexing. Then I'd wonder if you get a different chunk of compressed `data` when running a single file as when many other files are also running in parallel.

But if it's always the same file and the same raw bytes of `data` and `zlib.decompress` just hits an error when in parallel but not when running alone, then I don't know. (Different version of Python/zlib running on the remote machines when you distribute it than when you run it interactively on the head node?)

**Comment by asnaylor** [comment]
I also get the zlib.error when using dask instead of ProcessPoolExecutor. Yeah i'm running Uproot inside ProcessPool. 

It's does not always fail at the same file, it's a different file each time and only 1 file is failing each time i've tried it. It seems to be when it get's to around ~4600 files processed then one of the root files gives this zlib.error.

I just running a singular python script with ProcessPoolExecutor so there wouldn't be different versions of Python/zlib running as it should just be separate processes of the same python kernel.
zlib version:
```
zlib                      1.2.11            h516909a_1010    conda-forge
```

**Comment by jpivarski** [comment]
So running "on the head node" is not a different machine from "in parallel." (I thought maybe they were.)

If it's a different file each time, that looks like non-deterministic data. At a large enough scale, that would happen, and then the only recourse would be to try/retry. The decompression checksum provides some protection against corrupt data, but there are parts of the file that are not compressed/checksummed. Fortunately, they're small.

If you want to try to implement a per-chunk retry, it would be possible with the information that exists in that part of the code. [Chunk objects](https://uproot.readthedocs.io/en/latest/uproot.source.chunk.Chunk.html) have a `chunk.start` and `chunk.stop`, indicating their byte ranges in the file, and `chunk.source` is an object representing the file/HTTP/XRootD source, which has a [chunk method](https://uproot.readthedocs.io/en/latest/uproot.source.chunk.Source.html#chunk) to eagerly extract the chunk again.

```python
if failed:
    chunk = chunk.source.chunk(chunk.start, chunk.stop)
```

The hardest part would be to configure it in such a way that it doesn't retry forever. Chunks don't have a "number of retries" attribute.

Another thought, before getting to that: if it's a filesystem file (not HTTP or XRootD), have you tried passing

   * `file_handler=uproot.MemmapSource` or
   * `file_handler=uproot.MultithreadedFileSource` (with `num_workers=1` if need be) or
   * `path=open(filename, "rb")` (pass a Python file object so that Uproot doesn't get to decide how to access it)

as alternative options to [uproot.open](https://uproot.readthedocs.io/en/latest/uproot.source.chunk.Source.html#chunk)? Maybe the default memory-mapping is giving you problems. (Memory-mapping is an OS operation that sees across processes, maybe broken?)

**Comment by asnaylor** [comment]
Bizarre behaviour; split the 6000 root file list into 2, process them separately. 2nd part of the list gave me a zlib error, so i split that 3000 root file list (I re-ran the 2nd part of the list and again got a zlib error but on a different file; seem like the data was taken on the same day). I split the 2nd root file into 2, process those two root files lists separately but got no zlib errors at all when processing either of them.

**Comment by asnaylor** [comment]
Yeah sorry if i didn't make that clear, I'm just running on a single node. 

I can try implementing a retry X times try catch statement. 

Yeah i can try changing the file_hander and see if I stop getting the zlib error.

**Comment by jpivarski** [comment]
Retrying the `cls.decompress(data, block_uncompressed_bytes)` line (line 280) would do it if it's an error in the ZLIB function, but you'd have to re-load the chunk if it's something giving you the wrong data.

Also, you have the old `data` still in scope; you could see if it's giving you different bytestrings with repeated `chunk.source.chunk(chunk.start, chunk.stop)` calls. If so, that's evidence that you could send to NERSC, demonstrating that file-reads aren't deterministic.

**Comment by asnaylor** [comment]
One thing i noticed that using `file_handler=uproot.MultithreadedFileSource` with `num_workers=1` is quite alot slower than `file_handler=uproot.MemmapSource`. 

This time when running on an interactive node all different methods seemed to fail on the same file this time. I also tried to open the file the same way in a different compute node with the same python kernel and got a zlib.error. (previously i could open the bad zlib error file fine in a separate compute node with uproot)

Also tried to open this file in root and now i'm getting a zlib error:
```
root -l path_to_root_file.root
root [0]
Attaching file path_to_root_file.root as _file0...
R__unzip: error -5 in inflate (zlib)
Info in <TFile::GetStreamerInfoList>: cannot find the StreamerInfo record in file path_to_root_file.root
(TFile *) nullptr
```
So it seems like it's actually just a bad file, I was pretty sure that at the beginning it wasn't the same file everytime that had the zlib error but now it seems like only 1 file is giving the error.

**Comment by jpivarski** [comment]
Can you open that file (at this point in the TTree data, or maybe just all of the events) with ROOT?

**Comment by asnaylor** [comment]
At the time I couldn't open that particular root file with ROOT, I was getting a zlib error. That particular file has now been replaced at NERSC with an uncorrupted version and now i've been able to run uproot over all the files with ProcessPoolExecutor and Dask. So i'll close the issue as it seems like the issue was just 1 corrupted root file that was causing the problem, thanks
