### ISSUE TITLE
Superfluous "FutureWarning: XRootD 5.1.1 is not fully supported" when user does not use XRootD

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/uproot4#387]
uproot 4.0.11 produces a warning on every import:
```
[...]/reading.py:186: FutureWarning: XRootD 5.1.1 is not fully supported; either upgrade to 5.2.0+ or set

    open.defaults["xrootd_handler"] = uproot.MultithreadedXRootDSource

  warnings.warn(message, FutureWarning)
```

I am not using XRootD, so this warning is meaningless to me. Please only raise this warning when a user tries to actually use xrootd.

**Comment by jpivarski** [comment]
Hopefully #388 fixes this. The trick is that old versions of XRootD need to use one default (because of bugs in XRootD) and new versions need to use a different default, which is something that we don't want to have happen automatically because that would be too magical, so we make the issue visible to the user as a warning, which has to be raised when the default is set, i.e. at Uproot import time. This does not import XRootD; it is based on which version is installed. You must have an old version of XRootD _installed_, but you're not _using_ it, so you should not get the warning.

PR #388 makes the `uproot.open.defaults` dict into a slightly smarter dict that only gets/sets the `xrootd_handler` option if the user explicitly asks for it or assigns it or if ReadOnlyFile accesses it because a URL schema is "root://" (1d38083cb2e089d7d9b97ce0c027511d16e7f092). It should work regardless of whether the URL is in `uproot.open`, `uproot.iterate`, or `uproot.lazy`, though it will be tricky to test because the full behavior (when it shows the warning and when it doesn't) depends on whether XRootD is installed on one's system and which version it has, which is not easy to swap out in a pytest test.

As a first step, does the PR branch make the warning go away on your system? (The "has old XRootD installed; doesn't use it" case.)
