### ISSUE TITLE
uproot4 builds in EPEL/Fedora/etc

### ISSUE THREAD

**Issue by andriish** [scikit-hep/uproot4#401]
Hi @jpivarski ,

Would you consider to push the uproot4 to some large Linux distributives, e.g. RedHat EPEL + Fedora?
This would bring some advantages for the users, for instance one could have coherent installations in real systems and in containers with automatic updates. For the developers it could be interesting, as the massive rebuilds in Fedora and EPEL always test the latest versions of the software and these detect problems well ahead of time when typical users see them.
If you are interested, I would be happy to donate the .spec files I have for uproot 
https://github.com/andriish/HEPrpms/blob/master/python-uproot4/4.0.11/python-uproot4.spec

Best regards,

Andrii

**Comment by jpivarski** [comment]
If you want to manage that, go ahead.

One question, though: whenever there's a new version of Uproot, will you need to manually update the RedHat packages? That could be a lot of work. I usually don't install Python packages with my Linux distribution's package manager because Python packages update more frequently than the OS and large applications. As long as pip (or conda, but more likely pip) is available in EPEL + Fedora, why would those users want to install Uproot from the distro package?

Also, what kinds of problems could EPEL + Fedora testing discover that our continuous integration wouldn't catch? Uproot (intentionally) doesn't depend on much. New versions of Python or NumPy? (We test for that.) I'm not being antagonistic—I'm open to the possibility that this would be helpful—but I can't answer this question myself.

**Comment by andriish** [comment]
>  will you need to manually update the RedHat packages

Only the spec file. When there are no major changes and the package intentionally does not depend on many things 
the whole update is just an update of version string.
Here is a real world example https://src.fedoraproject.org/rpms/python-wrapt/blob/rawhide/f/python-wrapt.spec

> why would those users want to install Uproot from the distro package

There are few advantages, but those do exist.

a) Repositories offer a lot of stability/reproduciablility and assure that "everything is compatible with everything".
A good example could be  installing root and uproot4. It is easy to get root from the package manager e.g. on Fedora.
In the full installation root has numpy as a dependence, if I remember correctly.
Installing uproot via pip would bring its own version of numpy.
b) A system-wide installation.


> New versions of Python or NumPy?

That might be the simplest example. Sounds trivial, but they do that really good and on multiple less popular platforms as aarch64 or s390.

Best regards,

Andrii

**Comment by jpivarski** [comment]
Okay, just be aware that you're committing to updating the spec file at random times—whenever somebody finds even a minor bug, I push a new version of Uproot to PyPI.

> a) Repositories offer a lot of stability/reproduciablility and assure that "everything is compatible with everything".

For what definition of "compatible"? Running Uproot's test suite?

> A good example could be installing root and uproot4. It is easy to get root from the package manager e.g. on Fedora.
> In the full installation root has numpy as a dependence, if I remember correctly.
> Installing uproot via pip would bring its own version of numpy.

Just to be clear, there are no dependencies between ROOT and Uproot. Neither uses the other, so I don't know what compatibility would mean here, other than changes in the file format, which are intended to be independent of ROOT version (backward compatibility is a strong goal).

> b) A system-wide installation.

Pip is system-wide by default; you have to go through extra hoops to install a Python package for one user only. Conda isn't, though. I think conda has only a single-user model.

**Comment by andriish** [comment]
>  that you're 

Wait, wait :-). The question was if there is an interest.  I would be fine with maintaining the spec files but uproot4 should be there  first and that would take time. 

> there are no dependencies between ROOT

I know. Instead of ROOT one can name some other useful package with numpy as a dependency.
The compatibility I meant is the absense of dependency hell, multiple versions of same software, etc.

> Pip is system-wide by default

On many systems for security reasons the only accepted method for the system-wide installation is from the "trusted repositories". 
So I can ask cluster UI admins to install root, LHAPDF or similar things from EPEL system-wide, have a reproducible environment, never bother about updates and have empty .bashrc. But requests to install something  system-wide with pip will be rejected.

**Comment by jpivarski** [comment]
My interpretation of your first message was that you would maintain the spec files and the problem of getting Uproot into the EPEL/Fedora stack. Updating the spec by hand, even if only a digit in the version number, would eventually become burdensome—think about having to do it years from now when you've moved on to other projects—though perhaps it can be scripted, as I think the pip → conda-forge is.

I'm not volunteering to do it because I'm not convinced that there is a need, though I wouldn't be opposed if you do it. The only downside to me that I can imagine is if the Uproot version in EPEL/Fedora gets very old and people report bugs that have long been fixed, but I don't see that as being much of a problem, since I always ask for a reproducer and if it doesn't reproduce in the latest version, I'd just let them know that it's fixed in a new release. So that "downside to me" is not much of a downside.

Thus, go ahead and do this if you think it's worthwhile. If you're asking me to start the process of adding the package to EPEL/Fedora, sorry, I won't be doing that.

**Comment by andriish** [comment]
Hi @jpivarski ,

that is not how the EPEL or Fedora works in many aspects. There are well working procedures to deal with the potential issues you've (correctly!) described. Just taking the "bugreports on the old versions" as an example: In a very simplified picture, in Fedora, an absence of  updates/stalled issues  would mean "package is not maintained in Fedora" and it will be excluded from the future releases. Because Fedora supports only two last versions, bugreports can be created only for the last two versions+dev, i.e. releases that are not older than 1 year.

But the main thing is that you are fine with having uproot4 there. So I might try to put it in the EPEL or Fedora at some point and meanwhile will close this issue.
Thank you!

Best regards,

Andrii
