### ISSUE TITLE
std::vector<vector<float>> not correctly being read in .array() method

### ISSUE THREAD

**Issue by RohithKarur** [scikit-hep/uproot4#42]
Hello! I am analyzing a TTree where one branch is of type std::vector<vector<float>> is not being read. `file_str` is the ROOT file:

`ttree1 = uproot4.open(file_str)["CharmAnalysis"]`
`ttree1["TruthParticles_Selected_daughterInfoT__eta"].array()`

Here is the full stack trace:

```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<timed eval> in <module>

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/behaviors/TBranch.py in array(self, interpretation, entry_start, entry_stop, decompression_executor, interpretation_executor, array_cache, library)
   1284             interpretation_executor,
   1285             library,
-> 1286             arrays,
   1287         )
   1288 

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/behaviors/TBranch.py in _ranges_or_baskets_to_arrays(hasbranches, ranges_or_baskets, branchid_interpretation, entry_start, entry_stop, decompression_executor, interpretation_executor, library, arrays)
    493 
    494         elif isinstance(obj, tuple) and len(obj) == 3:
--> 495             uproot4.source.futures.delayed_raise(*obj)
    496 
    497         else:

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/source/futures.py in delayed_raise(exception_class, exception_value, traceback)
     31         exec("raise exception_class, exception_value, traceback")
     32     else:
---> 33         raise exception_value.with_traceback(traceback)
     34 
     35 

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/behaviors/TBranch.py in basket_to_array(basket)
    467                     branch.entry_offsets,
    468                     library,
--> 469                     branch,
    470                 )
    471         except Exception:

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/interpretation/objects.py in final_array(self, basket_arrays, entry_start, entry_stop, entry_offsets, library, branch)
    218                 for global_i in range(start, stop):
    219                     local_i = global_i - start
--> 220                     output[global_i - entry_start] = basket_array[local_i]
    221 
    222             start = stop

~/.local/cori/3.7-anaconda-2019.07/lib/python3.7/site-packages/uproot4/interpretation/objects.py in __getitem__(self, where)
     67         if uproot4._util.isint(where):
     68             byte_start = self._byte_offsets[where]
---> 69             byte_stop = self._byte_offsets[where + 1]
     70             data = self._byte_content[byte_start:byte_stop]
     71             chunk = uproot4.source.chunk.Chunk.wrap(self._branch.file.source, data)

IndexError: index 12344 is out of bounds for axis 0 with size 12344```

**Comment by jpivarski** [comment]
This is helpful—there's some inconsistency about how many entries a basket is believed to have (trying to get entry 12344 from a basket with 12344 entries... this might just be the first one that fails).

Could you send the file to that I can run it and look for the reason why there's this disagreement about how many items the basket has? If it's large or private, you can send it to me by email: jpivarski at GMail. Thanks!

**Comment by jpivarski** [comment]
Thanks for the file—you helped me fix a super-dumb error. (See the correction: four if-cases need to assign `basket_array`, one didn't. This is a cogent argument for test-coverage: none of my sample files enter this case. Then again, it's hard to do test-coverage when your inputs are ROOT files; you have to _find_ files that exhibit each of the cases you want to test. Thanks for sending me yours!)

Your original question was about performance. This branch takes 10 seconds to read on my computer. Since it's an inline object (vector of vectors), it's going through the slow Python code right now ([this](https://github.com/scikit-hep/uproot4/blob/b0dbc196cfe4e7536c490477712fca0ddd79718d/uproot4/containers.py#L471-L496)), though this will eventually be replaced by a compiled routine in Awkward 1. In the last plot of [this talk](https://figshare.com/articles/Vectorized_imperative_and_declarative_processing_of_Awkward_Arrays/11532795/1), your case is on the green line (original; no speedup) at the "doubly jagged" point, which is much lower than the "singly jagged" because of the difference in serialization format. The speedup shown in this plot from green line to orange line was made with experimental code that hasn't been integrated into the codebase, so it shows that we can expect a factor of 100 speedup when that's finished, bringing the "doubly jagged" case up to the same speed as "singly jagged." This is consistent in your file, because your `std::vector<float>` branches take 0.05‒0.08 seconds to load, which is that factor of 100 over 10 seconds.

As for when that will actually happen, it could be a matter of months, since getting Uproot 4 feature-complete is a higher priority. (Sorry!)
