### ISSUE TITLE
Reading jagged array output back in C++ ROOT

### ISSUE THREAD

**Issue by aminnj** [scikit-hep/uproot4#457]
I'm writing a jagged array to a ROOT file and reading it back either in pyroot or C++ ROOT.

This mostly round trips properly:
```python
>>> import uproot, awkward as ak
>>> print(uproot.__version__)
4.1.3
>>> print(ak.__version__)
1.4.0
>>> f = uproot.recreate("test.root")
>>> f["t"] = {"branch":  ak.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5], [6.6]])}
>>> f.close()

>>> import ROOT
>>> ch = ROOT.TChain("t")
>>> ch.Add("test.root")
>>> [list(evt.branch) for evt in ch] # works
[[1.1, 2.2, 3.3], [], [4.4, 5.5], [6.6]]
>>> ch.Draw("branch", "", "goff") # this should be 6
4
```

But with ROOT 6.24/06 I see
```cpp
root [2] t->Scan("*")
************************************
*    Row   * nbranch.n * branch.br *
************************************
*        0 *         3 *       1.1 *
*        1 *         0 *           *
*        2 *         2 *       4.4 *
*        3 *         1 *       6.6 *
************************************
(long long) 4
root [3] t->Scan("branch[0]")
************************
*    Row   * branch[0] *
************************
*        0 *       1.1 *
*        1 *           *
*        2 *       4.4 *
*        3 *       6.6 *
************************
(long long) 4
root [4] t->Scan("branch[1]")
************************
*    Row   * branch[1] *
************************
*        0 *       1.1 *
*        1 *           *
*        2 *       4.4 *
*        3 *           *
************************
(long long) 4
root [5] t->Scan("branch[2]")
************************
*    Row   * branch[2] *
************************
*        0 *       1.1 *
*        1 *           *
*        2 *           *
*        3 *           *
************************
(long long) 4
```
And `t->Draw("branch")` gives me a histogram filled with `[0, 1.1, 4.4, 6.6]`

**Comment by aminnj** [comment]
Without knowing what I'm really doing, I hardcoded
https://github.com/scikit-hep/uproot4/blob/03cb08ccb1f47ce0b082117f41a112af1ab403ee/src/uproot/writing/_cascadetree.py#L945-L948
to
```python
if datum["counter"] is None:
    dims = ""
else:
    dims = "[nbranch]"
```
and then the output file has the correct behavior in the ROOT REPL, which should match the output of this pyROOT script:
```python
from array import array
import ROOT

f = ROOT.TFile("blah.root", "recreate")
t = ROOT.TTree("t","")

n = array("i", [0])
b = array("d", 10*[0.])
t.Branch("nbranch", n, "nbranch/I")
t.Branch("branch", b, "branch[nbranch]/D")

vals = [[1.1, 2.2, 3.3], [], [4.4, 5.5], [6.6]]
for e in vals:
    n[0] = len(e)
    for i in range(len(e)):
        b[i] = e[i]
    t.Fill()
t.Write()
f.Close()
```

**Comment by jpivarski** [comment]
Doesn't this:

```python
>>> import ROOT
>>> ch = ROOT.TChain("t")
>>> ch.Add("test.root")
>>> [list(evt.branch) for evt in ch] # works
[[1.1, 2.2, 3.3], [], [4.4, 5.5], [6.6]]
```

mean that ROOT is reading it back correctly? (I was taking that as a definition of "correct".) PyROOT is ROOT—the Python interface shouldn't affect anything in the I/O layer. For instance, in PyROOT, you can say

```python
>>> ch.Scan("*")
```

and the output ought to be exactly the same as in C++ ROOT.

The Uproot code you changed only changes the leaf title from `"branch"` to `"branch[nbranch]"`. Does ROOT's `TTree::Scan` behavior depend on the leaf title? If so, then perhaps a more appropriate title would be

```python
  if datum["shape"] == (): 
    dims = ""
  else:
    dims = "".join("[" + str(x) + "]" for x in datum["shape"])

  if datum["counter"] is not None:
      dims = "[nbranch]" + dims
```

so that the variable-length dimension would be followed by the fixed-length dimensions (if either exist).

It should be possible to perform the same experiments in ROOT. After creating the branch,

```python
t.GetBranch("branch").GetListOfLeaves()[0].SetTitle("anything")
```

should let you set the leaf title to anything. Does changing it to an arbitrary value break `TTree::Scan`?

**Comment by aminnj** [comment]
I would say it's "mostly correct". If you only get back the values with
`[list(evt.branch) for evt in ch]` then it's correct, but `ch.Scan()/ch.Draw()` (pyROOT) will give the same (incorrect) behavior as on the ROOT REPL since as you say they're calling the same underlying code:
```python
>>> ch.Scan("*")
************************************
*    Row   *   nbranch *    branch *
************************************
*        0 *         3 *       1.1 *
*        1 *         0 *           *
*        2 *         2 *       4.4 *
*        3 *         1 *       6.6 *
************************************
>>> ch.Draw("Length$(branch)") # gives 4 entries in the 1 bin
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
>>> ch.Draw("branch", "", "goff") # should give 6
4
```

Thanks for the line of code. Indeed it gives the same result as my `dims = ...` modification:
```python
>>> ch.GetBranch("branch").GetListOfLeaves()[0].SetTitle("branch[nbranch]")
>>> ch.Scan("*")
***********************************************
*    Row   * Instance *   nbranch *    branch *
***********************************************
*        0 *        0 *         3 *       1.1 *
*        0 *        1 *         3 *       2.2 *
*        0 *        2 *         3 *       3.3 *
*        1 *        0 *         0 *           *
*        2 *        0 *         2 *       4.4 *
*        2 *        1 *         2 *       5.5 *
*        3 *        0 *         1 *       6.6 *
***********************************************
```

**Comment by aminnj** [comment]
Not sure how `[list(evt.branch) for evt in ch]` gives the right answer when even TTreeReader fails:
```cpp
root [1] TTreeReader reader(t);
root [2] TTreeReaderArray<double> b(reader, "branch");
root [3] while (reader.Next()) std::cout << b.GetSize() << " " << b[0] << std::endl;
1 1.1
1 1.1
1 4.4
1 6.6
```

**Comment by jpivarski** [comment]
The branch's leaf has a `fLeafCount` member that points to its counter, but `TTree::Scan`, `TTree::Draw`, and `TTreeReader` seem to be ignoring it or not using it exclusively to find the counter; you've shown that they depend on the branch's leaf's title as well. The title is not merely informative; those functions are evidently parsing it for behavior. PR #458 adds this information to the titles that Uproot writes so that these ROOT functions will work.

(Ironically, the counter is not even needed. The information about how many subentries each entry has is also contained in the baskets of the jagged branch as offsets, rather than counts. Uproot completely ignores counters when reading jagged arrays.)

**Comment by aminnj** [comment]
Makes sense. Thanks for the fast fix!
