### ISSUE TITLE
TBaskets from one TTree get overwritten by another TTree

### ISSUE THREAD

**Issue by duncanmmacleod** [scikit-hep/uproot4#474]
Attempting to `update()` a newly-created file with another TTree raises an `AssertionError`.

```python
>>> import numpy
>>> import uproot
>>> print(uproot.__version__)
4.1.3
>>> b1 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> b2 = [0.0, 1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]
>>> with uproot.recreate("test.root", compression=None) as fout:
...     tree = fout.mktree("t", {"b1": numpy.int32, "b2": numpy.float64}, "title")
...     tree.extend({"b1": b1, "b2": b2})
...
>>> with uproot.update("test.root") as fout:
...     tree = fout.mktree("t2", {"b1": numpy.int32, "b2": numpy.float64}, "title")
...     tree.extend({"b1": b1, "b2": b2})
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/duncan/opt/miniconda3/envs/py39/lib/python3.9/site-packages/uproot/writing/writable.py", line 171, in update
    cascading = uproot.writing._cascade.update_existing(
  File "/home/duncan/opt/miniconda3/envs/py39/lib/python3.9/site-packages/uproot/writing/_cascade.py", line 2435, in update_existing
    freesegments_key = Key.deserialize(
  File "/home/duncan/opt/miniconda3/envs/py39/lib/python3.9/site-packages/uproot/writing/_cascade.py", line 442, in deserialize
    assert fCycle > 0
AssertionError
```

I presume this is user error, so can someone please point me in the right direction to be able to append new trees to an existing file?

**Comment by jpivarski** [comment]
Assertions (and NotImplementedErrors) are not user errors. ValueErrors and IndexErrors usually are, and often KeyErrors are (trying to read an object that doesn't exist, of a misspelling), but internal missing values are also fairly common, so it's hard to say with KeyErrors. However, assertions are deliberately put into the code by a programmer who thinks, "This can't happen, so I'll assert to stop a runaway process." I can't think of a legitimate reason an assertion would be the user's fault.

This one is complaining that the "cycle number" of an object, probably that TTree because it's the only thing around, is 0. They're supposed to start at 1, so either that was a mistake in the writing step or the reading step is not on the byte it thinks it is ("got off the rails"), and it's interpreting some 0 as the cycle number. I'll take a look.
