### ISSUE TITLE
Wrong binning obtained from to_hist()/to_boost()

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/uproot4#495]
```python
import uproot
import numpy as np

hist = np.histogram([], bins=22, range=(0, 22))
# Using to_writable directly to skip writing and reading hist to/from a file
uproot_hist = uproot.writing.to_writable(hist)
hist_hist = uproot_hist.to_hist()
```

Now doing `np.all(uproot_hist.axis(0).edges() == hist[1])` will give `True`. However `np.all(hist_hist.axes[0].edges == hist[1])` will give `False`. Somehow the edge at index 15 got moved slightly. I also observe this when `uproot_hist` is coming from a file ROOT produced. The same happens also with `to_boost`. If this binning is used for other histograms, it may yield very different results after being filled.
I think `to_hist` and `to_boost` should only change the representation of the histogram, they should not modify the edges or contents.

**Comment by jrueb** [comment]
Used versions:
Uproot version 4.1.3
boost_histogram version 1.2.1
hist version 2.5.1
numpy version 1.21.0

**Comment by jpivarski** [comment]
Yes, it's not bit-for-bit the same:

```python
>>> assert hist[1].tolist() == list(range(23))   # okay
>>> assert uproot_hist.axis(0).edges().tolist() == list(range(23))   # okay
>>> assert uproot_hist.to_hist().axes[0].edges.tolist() == list(range(23))   # uh-oh!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
```

But it's in the least significant bit:

```python
>>> uproot_hist.to_hist().axes[0].edges.tolist()
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 14.999999999999998, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0]
```

All NumPy histograms have in-principle variable binned edges (each edge is explicitly given as a floating-point number), but boost-histogram/hist (and ROOT) have the option of regular binning (edges are defined in terms of a min, max, and number of bins). The variable bins in this NumPy histogram are close enough that they're converted into a boost-histogram/hist Regular axis:

https://github.com/scikit-hep/uproot4/blob/8da183190c35804ee3d37e7d3cd5d1be83877a34/src/uproot/behaviors/TH1.py#L27-L37

```python
>>> uproot_hist.to_hist().axes[0]
Regular(22, 0, 22, name='xaxis', label='xaxis')
```

Somewhere within boost-histogram/hist, the calculation of edges from the min, max, and number of bins has some roundoff error. At this level of precision, I'm not surprised. I don't think the point where this happens is anywhere in the Uproot codebase (because we just hand off the min, max, and number of bins; boost-histogram/hist calculates the specific edges from that), but I also don't think it's going to be a very useful thing to dive in and find that point. Even if this round-off gets "fixed," there's probably other round-off errors on this level of precision. We generally don't expect bit-by-bit agreement when two codebases perform algebraically equivalent operations with (very likely) different low-level instructions.

Anyway, if it's alright, I'm going to close this issue here.
