### ISSUE TITLE
Writing, Reading then Rewriting Numpy "Object"/Jagged arrays produces missing branch error

### ISSUE THREAD

**Issue by djdthompson** [scikit-hep/uproot4#498]
Hello,
I think I've found an issue with jagged arrays when creating TTrees in version 4.17 of uproot (with version 1.21.0 of Numpy).

I found this issue when trying to cut and rewrite numpy "object" arrays containing arrays of different lengths which were loaded from JaggedArrays initially. I've recreated it below with a quick write, read and re-write example and the output and error message below that (in this example I've created my own version of the tuple for quicker bug testing).

Essentially, the TTree creates these new "nVariable" branches containing information about the length of each array in a jagged array. I didn't expect this behaviour for numpy arrays, as in the [documentation](https://uproot.readthedocs.io/en/latest/basic.html#writing-ttrees-to-a-file) it only discusses this for Awkward arrays (but this may not be a bug). When trying to read in and rewrite this example TTree to a new file uproot gives a "missing branch" error even though the branch is clearly there. Looking at the error message I guess the "metadata" used in mktree is missing these newly created branches, making me wonder whether they are intentional?

I tried the same example but reading the ntuple in with library="ak" and this produces a new error with `fields of a record must be NumPy types, though the record itself may be in a jagged array` 

Code:
```python
import numpy as np
import uproot as up
print(np.__version__) #1.21
print(up.__version__) #4.17

#first going to make a tuple with jagged arrays
with up.recreate("jaggedTest.root") as w:
    w["testTree"]={"arr1":np.array([[4,2,1],[6,432,89,54],[3,2],[88]],dtype=object),
                  "arr2":np.array([[21,53,1,45],[34,42,39],[9,1,37,98],[83]],dtype=object),
                  "arr3":np.array([34,1012,38,1040]),
                  "arr4":np.array([3.4,3.8,10.12,10.40])}
    
    
with up.open("jaggedTest.root:testTree",library="np") as f:
    print(f.show())
    
#now read it in and write it to new tuple with cuts
with up.recreate("jaggedTestCut.root") as w:
    intialCheck=True #check to instruct uproot to create the new tree first before extending it
    
    #using iterate as this is where issue was found
    #step size of two so that the above is split into sections
    #cut made as thought this could be issue, it isn't.
    for batch in up.iterate([a+":testTree" for a in ["jaggedTest.root"]],
        cut="arr3>50",library="np",step_size=2):
        print("Printing Batch to Load ",batch)
        #can see that the new "nVar" arrays have been created when making the above ntuple

        if initialCheck:
            #but it's as if it's not even stored in the metadata as can't load the batch in.
            w["testTree"]=batch
            print(w["testTree"])
            initialCheck=False
        else:
            #usually fails here, but was using a ROOT made tuple so no "nVariables"
            #until after loading first batch into "w"
            w["testTree"].extend(batch)
        
```

Output:

```text
1.21.0
4.1.7
name                 | typename                 | interpretation                
---------------------+--------------------------+-------------------------------
narr1                | int32_t                  | AsDtype('>i4')
arr1                 | int64_t[]                | AsJagged(AsDtype('>i8'))
narr2                | int32_t                  | AsDtype('>i4')
arr2                 | int64_t[]                | AsJagged(AsDtype('>i8'))
arr3                 | int64_t                  | AsDtype('>i8')
arr4                 | double                   | AsDtype('>f8')
None
Printing Batch to Load  {'narr1': array([4], dtype=int32), 'arr1': array([array([  6, 432,  89,  54])], dtype=object), 'narr2': array([3], dtype=int32), 'arr2': array([array([34, 42, 39])], dtype=object), 'arr3': array([1012]), 'arr4': array([3.8])}
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-26-d722a337c359> in <module>
     30         if initialCheck:
     31             #but it's as if it's not even stored in the metadata as can't load the batch in.
---> 32             w["testTree"]=batch
     33             print(w["testTree"])
     34         else:

/.../lib/python3.9/site-packages/uproot/writing/writable.py in __setitem__(self, where, what)
    965         if self._file.sink.closed:
    966             raise ValueError("cannot write data to a closed file")
--> 967         self.update({where: what})
    968 
    969     def __delitem__(self, where):

/.../lib/python3.9/site-packages/uproot/writing/writable.py in update(self, pairs, **more_pairs)
   1466                 directory = directory[item]
   1467 
-> 1468             uproot.writing.identify.add_to_directory(v, name, directory, streamers)
   1469 
   1470         self._file._cascading.streamers.update_streamers(self._file.sink, streamers)

/.../lib/python3.9/site-packages/uproot/writing/identify.py in add_to_directory(obj, name, directory, streamers)
    148     if is_ttree:
    149         tree = directory.mktree(name, metadata)
--> 150         tree.extend(data)
    151 
    152     else:

/.../lib/python3.9/site-packages/uproot/writing/writable.py in extend(self, data)
   1745             **As a word of warning,** be sure that each call to :ref:`uproot.writing.writable.WritableTree.extend` includes at least 100 kB per branch/array. (NumPy and Awkward Arrays have an `nbytes <https://numpy.org/doc/stable/reference/generated/numpy.ndarray.nbytes.html>`__ property; you want at least ``100000`` per array.) If you ask Uproot to write very small TBaskets, it will spend more time working on TBasket overhead than actually writing data. The absolute worst case is one-entry-per-:ref:`uproot.writing.writable.WritableTree.extend`. See `#428 (comment) <https://github.com/scikit-hep/uproot4/pull/428#issuecomment-908703486>`__.
   1746         """
-> 1747         self._cascading.extend(self._file, self._file.sink, data)
   1748 
   1749     def show(

/.../lib/python3.9/site-packages/uproot/writing/_cascadetree.py in extend(self, file, sink, data)
    586                     actual_branches[datum["fName"]] = provided.pop(datum["fName"])
    587                 else:
--> 588                     raise ValueError(
    589                         "'extend' must be given an array for every branch; missing {0}".format(
    590                             repr(datum["fName"])

ValueError: 'extend' must be given an array for every branch; missing 'narr1'       
```

**Comment by jpivarski** [comment]
Regardless of whether the jagged array is an Awkward Array or is a NumPy dtype="O" array, there has to be a counter branch. This counter branch is not needed for Uproot to read the data back, but it is needed for ROOT to read the data back. In particular, you wouldn't be able to do this workflow in ROOT without it:

```python
>>> import uproot
>>> file = uproot.recreate("tmp.root")
>>> file["tree"] = {"branch": [[1.1, 2.2, 3.3], [], [4.4, 5.5]]}
```

```c++
root [0] auto file = new TFile("tmp.root")
(TFile *) @0x7ffd501efaa0
root [1] TTree* tree
(TTree *) nullptr
root [2] file->GetObject("tree", tree)
root [3] int maxlength = tree->GetBranch("branch")->GetLeaf("branch")->GetLeafCount()->GetMaximum()
(int) 3
root [4] double* buffer = new double[maxlength]
(double *) 0x55e17a709000
root [5] tree->SetBranchAddress("branch", &buffer)
(int) 0
```

(etc.) Traditional ROOT TTree-reading reuses the same array buffer as it steps through entries, and it needs to know how large to allocate this buffer before running over any data. The maximum size is stored in the counter leaf. Also, some of the methods that I use to test reading in ROOT (`TTree::Scan`, iteration in PyROOT) don't work without the counter leaf.

Given that the counter leaf has to be there, your problem is that the generated counters conflict with the counters that you're providing by passing the array from `uproot.iterate` directly into the output. That is, the output of `uproot.iterate` includes the counters as arrays, and writing takes both those arrays and also generates new counters from your jagged arrays.

(Parenthetically, any NumPy arrays with dtype="O" are internally converted into Awkward Arrays to do these manipulations. You're not saving any time or reducing dependencies by making them NumPy arrays. The opposite, actually.)

PR #499 checks for conflicts between explicitly provided arrays and generated counters. If they're exactly the same, it only writes it once and all is well. If they differ, perhaps because a cut was applied to nested lists within a jagged array but not a purported counter, then it will raise a ValueError. This doesn't save you from having to look at the data extracted from the input and be conscious of what you write to the output, but the alternative would be to silently overwrite explicit arrays with generated counters, which would cause a subtle bug for somebody.
