### ISSUE TITLE
Get Wrong Branches from a tree

### ISSUE THREAD

**Issue by OneSkyknight** [scikit-hep/uproot4#508]
```python
>>> import uproot
>>> uproot.__version__
>>>'4.1.8'
```
I get different results from uproot and root_numpy. See below:

```
import ROOT as R
import numpy as np
import uproot

tree = uproot.open('EH1.root:IBD;1')
Cut1="AD==2 & (PromptZ > 0)"
data1=tree.arrays(["EPrompt"],cut=Cut1, library="np")
print(data1)
print(len(data1['EPrompt']))
print("###")
import root_numpy 
F=R.TFile("EH1.root")
tree=F.Get("IBD;1")
Cut2="AD==2 && (PromptZ > 0)"
data2=root_numpy.tree2array(tree,
        branches=['EPrompt'],
        selection=Cut2,
        )
print(data2)
print(len(data2))
```

results:
```
{'EPrompt': array([], dtype=float64)}
0
###
[(0.4171901 ,) (0.52765977,) (2.66819382,) ... (0.83053756,) (0.84282863,)
 (0.35761279,)]
18052763
```

Why uproot can not get the right array? Cut1 is for uproot and Cut2 is for root_numpy.

**Comment by jpivarski** [comment]
Might it be parentheses around the `AD==2`?

In Python, `AD==2 & (PromptZ > 0)` means `AD` equality-comparison with `2 & (PromptZ > 0)`, where `&` is bitwise-and. The `==` equality-comparison has lower operator precedence than `&` bitwise-and.

Here's a dump of Python's syntax tree for that expression:

```python
>>> import ast
>>> print(ast.dump(ast.parse("AD==2 & (PromptZ > 0)"), indent=4))
Module(
    body=[
        Expr(
            value=Compare(
                left=Name(id='AD', ctx=Load()),
                ops=[
                    Eq()],
                comparators=[
                    BinOp(
                        left=Constant(value=2),
                        op=BitAnd(),
                        right=Compare(
                            left=Name(id='PromptZ', ctx=Load()),
                            ops=[
                                Gt()],
                            comparators=[
                                Constant(value=0)]))]))],
    type_ignores=[])
```

The `Name(id='AD', ctx=Load())` (representing the "`AD`" part of the expression) is being equality-compared (`Compare( ... ops=[Eq()], ...)`) with a tree computed by the binary operation (`BinOp`) that is the bitwise and (`BitAnd()`).

**Okay, maybe that was too much information.** Maybe you just want to try

```python
Cut1="(AD==2) & (PromptZ > 0)"
```

By contrast, `Cut2="AD==2 && (PromptZ > 0)"` is TTreeFormula syntax (why `&&` is needed instead of `&`, it's a different language). The `&&` means logical-and, and `==` has a higher operator precedence than `&&`.

My biggest pet peeve about Python+NumPy is that there's no operator for array-at-a-time logical-and. Bitwise-and works, since the arrays are just booleans, but the operator precedence is ~~wrong~~ highly unexpected.

One of the open items we'd like to fill is to get [formulate](https://github.com/scikit-hep/formulate) up to date so that Uproot's cut strings can use TTreeFormula syntax instead of Python syntax (as an option, default being TTreeFormula).

**Comment by OneSkyknight** [comment]
> Might it be parentheses around the `AD==2`?
> 
> In Python, `AD==2 & (PromptZ > 0)` means `AD` equality-comparison with `2 & (PromptZ > 0)`, where `&` is bitwise-and. The `==` equality-comparison has lower operator precedence than `&` bitwise-and.
> 
> Here's a dump of Python's syntax tree for that expression:
> 
> ```python
> >>> import ast
> >>> print(ast.dump(ast.parse("AD==2 & (PromptZ > 0)"), indent=4))
> Module(
>     body=[
>         Expr(
>             value=Compare(
>                 left=Name(id='AD', ctx=Load()),
>                 ops=[
>                     Eq()],
>                 comparators=[
>                     BinOp(
>                         left=Constant(value=2),
>                         op=BitAnd(),
>                         right=Compare(
>                             left=Name(id='PromptZ', ctx=Load()),
>                             ops=[
>                                 Gt()],
>                             comparators=[
>                                 Constant(value=0)]))]))],
>     type_ignores=[])
> ```
> 
> The `Name(id='AD', ctx=Load())` (representing the "`AD`" part of the expression) is being equality-compared (`Compare( ... ops=[Eq()], ...)`) with a tree computed by the binary operation (`BinOp`) that is the bitwise and (`BitAnd()`).
> 
> **Okay, maybe that was too much information.** Maybe you just want to try
> 
> ```python
> Cut1="(AD==2) & (PromptZ > 0)"
> ```
> 
> By contrast, `Cut2="AD==2 && (PromptZ > 0)"` is TTreeFormula syntax (why `&&` is needed instead of `&`, it's a different language). The `&&` means logical-and, and `==` has a higher operator precedence than `&&`.
> 
> My biggest pet peeve about Python+NumPy is that there's no operator for array-at-a-time logical-and. Bitwise-and works, since the arrays are just booleans, but the operator precedence is ~wrong~ highly unexpected.
> 
> One of the open items we'd like to fill is to get [formulate](https://github.com/scikit-hep/formulate) up to date so that Uproot's cut strings can use TTreeFormula syntax instead of Python syntax (as an option, default being TTreeFormula).

You are exactly right! When I use Cut1="(AD==2) & (PromptZ > 0)", it works.
Many thanks to your detailed explanation!
Great project!

**Comment by jpivarski** [comment]
I'm glad it's working for you!
