### ISSUE TITLE
"'TAxis' object layout differs from 'DynamicModel'" when unpickleing histograms created using from_pyroot

### ISSUE THREAD

**Issue by jlabounty** [scikit-hep/uproot4#520]
Hello,

I have been encountering an error when trying to pickle/unpickle some histograms. As an example, I have two scripts: one which creates a histogram and pickles it and the other which opens the file and reads it in. I know I could store these in root files, but since I was manipulating hist objects originally I used pickle for convenience. 

The odd thing is that opening the pickle file in the same script in which is was created works as expected, but opening it in a different script does not.

The first script is:
```
import ROOT as r
import uproot
import pickle

print(f"{uproot.__version__=}")
h = r.TH1D("h", 'Example histogram', 100,0,1)

h2 = uproot.from_pyroot(h) #.to_hist() # this was the original version, and the same error occurs when trying to pickle a hist object
print(h2, type(h2))

with open("out.pickle", 'wb') as f:
    pickle.dump(h2, f)

print("Opening the pickled file in the same script works")

with open("out.pickle", 'rb') as f:
    ding = pickle.load(f)

print(ding, type(ding))
```
And this works as expected:
```
(vscode) jlab@SB3:~/uproot_issue$ python --version
Python 3.9.7
(vscode) jlab@SB3:~/uproot_issue$ python create_file.py 
uproot.__version__='4.1.2'
<TH1D (version 3) at 0x7ffa4eefff10> <class 'uproot.dynamic.Model_TH1D_v3'>
Opening the pickled file in the same script works
<TH1D (version 3) at 0x7ffa4d4f2af0> <class 'uproot.dynamic.Model_TH1D_v3'>
(vscode) jlab@SB3:~/uproot_issue$ 
```

When I try to open the same output file in the other script, however:
```
import pickle
import uproot

print("Opening the pickled file in another script does not work")
with open("out.pickle", 'rb') as f:
    ding = pickle.load(f)

print(ding, type(ding))
```
yields the error:
```
(vscode) jlab@SB3:~/uproot_issue$ python open_file.py 
Opening the pickled file in another script does not work
Traceback (most recent call last):
  File "/home/jlab/uproot_issue/open_file.py", line 6, in <module>
    ding = pickle.load(f)
  File "/home/jlab/miniconda3/envs/vscode/lib/python3.9/site-packages/uproot/model.py", line 1637, in __setstate__
    cls.__bases__ = (
TypeError: __bases__ assignment: 'TAxis' object layout differs from 'DynamicModel'
(vscode) jlab@SB3:~/uproot_issue$ 
```

I have reproduced this on python 3.8 and 3.9, and uproot versions 4.1.2 and 4.1.8. Thank you!

[example.zip](https://github.com/scikit-hep/uproot4/files/7644580/example.zip)

**Comment by jpivarski** [comment]
It depends on the Python process because an object made `from_pyroot` has a dynamically created class: the data from PyROOT may be a type we've never seen before, so we have to create the class object before creating the instance.

Here's a histogram made entirely with non-dynamic classes: `to_writable` makes an object using some hard-coded classes (i.e. the standard way) because the object is something we might want to write to a file, so we have to know how to serialize it.

```python
>>> import uproot
>>> import numpy as np
>>> h_not_dynamic = uproot.to_writable(np.histogram([1, 2, 3]))
>>> type(h_not_dynamic).mro()
[<class 'uproot.models.TH.Model_TH1D_v3'>,
 <class 'uproot.behaviors.TH1.TH1'>,
 <class 'uproot.behaviors.TH1.Histogram'>,
 <class 'uproot.model.VersionedModel'>,
 <class 'uproot.model.Model'>, <class 'object'>]
```

Here's an object made `from_pyroot`. In principle, it could have any type from the ROOT library or even types defined by users. We create a class object for it and put that in the `uproot.dynamic` namespace, so that we can instantiate the histogram.

```python
>>> import ROOT
>>> h_root = ROOT.TH1D("h", "", 100, 0, 1)
>>> h_dynamic = uproot.from_pyroot(h_root)
>>> type(h_dynamic).mro()
[<class 'uproot.dynamic.Model_TH1D_v3'>,
 <class 'uproot.behaviors.TH1.TH1'>,
 <class 'uproot.behaviors.TH1.Histogram'>,
 <class 'uproot.dynamic.Model_TH1D_v3'>,
 <class 'uproot.model.VersionedModel'>,
 <class 'uproot.model.Model'>, <class 'object'>]
```

We can pickle them both:

```python
>>> import pickle
>>> pickle.dump(h_not_dynamic, open("h_not_dynamic.pkl", "wb"))
>>> pickle.dump(h_dynamic, open("h_dynamic.pkl", "wb"))
```

and if I tried to unpickle them, they'd both be fine (you've already seen that). The `uproot.dynamic` namespace has a lot of classes in it, created by the `from_pyroot`.

```python
>>> dir(uproot.dynamic)
['Model_TAttAxis',
 'Model_TAttAxis_v4',
 'Model_TAttFill',
 'Model_TAttFill_v2',
 'Model_TAttLine',
 'Model_TAttLine_v2',
 'Model_TAttMarker',
 'Model_TAttMarker_v2',
 'Model_TAxis',
 'Model_TAxis_v10',
 'Model_TH1',
 'Model_TH1D',
 'Model_TH1D_v3',
 'Model_TH1_v8',
 'Model_TNamed',
 'Model_TNamed_v1',
 'Model_TObject',
 'Model_TObject_v1',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']
```

When we start a new Python process, the `uproot.dynamic` namespace is empty:

```python
>>> import uproot
>>> dir(uproot.dynamic)
['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__']
```

What's supposed to happen is that the unpickler tries to access a class from the `uproot.dynamic` namespace and then this code (the only thing in that file) generates it on demand:

https://github.com/scikit-hep/uproot4/blob/8ae497a89ec92f06724980fccafa1c4286ce6040/src/uproot/dynamic.py#L17-L24

Python's unpickler is something we can't control. It looks at the class name in the pickle data and tries to find such a class. If it doesn't find the class, it gives up before we have a chance to do anything about that; that's why any attempt to access a name from `uproot.dynamic` results in a subclass of `uproot.model.DynamicModel` being created on the spot (unless such a subclass has already been created once).

So far, so good, but in the unpickling process, we know that this histogram has convenience methods ([uproot.behaviors.TH1.TH1](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TH1.TH1.html)) but the dynamic class has been created without them. We should be able to change the `__bases__` to add them, since behaviors are stateless collections of methods (they're "mixins"). But Python is complaining about that. I don't know why. I don't think it violates any of the rules [described here](https://stackoverflow.com/a/3308895/1623645).

I'm going to look into it.

**Comment by jpivarski** [comment]
I found it. The TAxis behavior was a subclass of `collections.abc.Sequence`, which apparently isn't a normal Python object. So that's a new rule for us: behaviors can't be collections. PR #521.

**Comment by jlabounty** [comment]
Thanks so much for the speedy response!
