### ISSUE TITLE
Manually set Interpretation as multi dim Array

### ISSUE THREAD

**Issue by rklasen** [scikit-hep/uproot4#553]
This is an addition to the Stack Overflow question I posted [here](https://stackoverflow.com/questions/70878968/set-interpretation-as-multi-dim-array-when-reading-tbranchelement).

I'm using upRoot Version: `4.1.7`. I've attached an example ROOT file as issue-553.txt.

I have a file that contains TGeoTracks on one branch element. TGeoTracks have two private members that I'm interested in, a number of points and an array that's 4*nPoints (https://root.cern.ch/doc/master/TGeoTrack_8h_source.html#l00040). 

```cpp
private :
   Int_t          fPointsSize; // capacity of points array
   Int_t          fNpoints;    // number of stored points
   Double_t      *fPoints;     //[fNpoints] array of points (x,y,z,t) belonging to this track
```

This is that the ROOT file looks like in the TBrowser:

[![enter image description here][1]][1]

Note that the interpretation in the TBrowser is slightly misleading since all four elements per event are stored in the same histogram.

Now, I'm trying to read the file with uproot. The default interpreation for this branch element was wrong:

```python
mcFileThin1_5 = uproot.open("/media/CacheDrive2TB/Arbeit/PandaRoot/macro/detectors/lmd/testFullChain-thinKapton/mom-1_5/Lumi_MC_0.root")
startXarray = mcFileThin1_5["pndsim/GeoTracks.fPoints"]
print(startXarray.interpretation)

AsObjects(AsArray(True, False, AsArray(False, True, dtype('>f8'), ()), ()))
```

So i tried with a custom interpretation:

```python
mcFileThin1_5 = uproot.open("/media/CacheDrive2TB/Arbeit/PandaRoot/macro/detectors/lmd/testFullChain-thinKapton/mom-1_5/Lumi_MC_0.root")
startXarray = mcFileThin1_5["pndsim/GeoTracks.fPoints"]

dtype = np.dtype([("x", ">f8"),("y", ">f8"),("z", ">f8"),("t", ">f8")])
interpret = uproot.AsDtype(dtype)
arr = mcFileThin1_5["pndsim/GeoTracks.fPoints"].array(interpret)
```

But that fails:

```
ValueError: basket 0 in tree/branch /pndsim;4:GeoTracks/GeoTracks.fPoints has the wrong number of bytes (22902) for interpretation AsDtype("[('x', '>f8'), ('y', '>f8'), ('z', '>f8'), ('t', '>f8')]")
in file /media/CacheDrive2TB/Arbeit/PandaRoot/macro/detectors/lmd/testFullChain-thinKapton/mom-1_5/Lumi_MC_0.root
```

How can I specify the interpretation of this branch element to be four doubles per point?

  [1]: https://i.stack.imgur.com/WrhRH.png

**Comment by rklasen** [comment]
[issue-553.txt](https://github.com/scikit-hep/uproot4/files/8003033/issue-553.txt)

**Comment by jpivarski** [comment]
I don't know what to make of this file. (**Edit:** by the end of this comment, I do. Sorry for the stream-of-consciousness.)

By looking at the raw data, it's clear that the actual numbers start after the first byte, so it would seem that the appropriate interpretation would be

```python
uproot.AsJagged(uproot.AsDtype(
    np.dtype([("x", ">f8"),("y", ">f8"),("z", ">f8"),("t", ">f8")])
), header_bytes=1)   # skip 1 byte in each entry
```

or equivalently, the `AsArray(...)` that it originally expected. However, the data in each entry is an apparently random number of bytes—hopefully always larger than `fNPoints * 4 * 8`. The reason both of these interpretations are failing is because it can't cast the remaining bytes as 8-byte floats. Even if each entry's binary blob were at least a multiple of 8 bytes or 32 bytes, the resulting array would then have too much data per entry.

Here's some of my debugging code, trying to go through it very carefully:

```python
import uproot
import numpy as np
branch = uproot.open("issue-553.root")["pndsim/GeoTracks.fPoints"]
basket = branch.basket(0)
interpretation = uproot.AsJagged(uproot.AsDtype(np.dtype(">f8")), header_bytes=1)
interpretation.basket_array(basket.data, basket.byte_offsets, basket, branch, {}, 0, uproot.interpretation.library.NumPy)
# ValueError because the basket.byte_offsets don't correspond to multiples of 8 bytes
```

The first entry has a multiple of 8 bytes (after skipping the 1-byte header), but the second does not. This first `basket` has four entries, which have to be interpreted together.

There doesn't seem to be any way to know how much data to interpret as points without looking at `fNpoints`, a _totally different branch_. So I guess this is something that would require a "custom streamer," out of scope for Uproot because custom streamers are written in C++, not encoded by the TStreamerInfo in the file. This particular example seems pretty simple, so we should be able to hack something together, but this is at the limits of what Uproot would ever be able to do.

I just noticed that `fNpoints` is a jagged array:

```python
>>> tree = uproot.open("issue-553.root:pndsim")
>>> tree["GeoTracks/GeoTracks.fNpoints"].array()
<Array [[464], [248, 8, 8, ... 12, 8], [464]] type='100 * var * uint32'>
```

so these points would have to be interpreted as an array of `100 * var * var * {x: float64, y: float64, z: float64, t: float64}` (doubly nested jagged array). That's why the expected interpretation involved two nested `AsArrays`! But it couldn't interpret it without external information—the `fNpoints`—so it didn't know where to stop looping. We'll have to manually pull that information into it.

To start with, we can get the raw bytes for any entry with [uproot.TBranch.debug_array](https://uproot.readthedocs.io/en/latest/uproot.behaviors.TBranch.TBranch.html#debug-array). Using that in production code is a hack. I was misled by the first entry (`0`) because it has only one sub-entry, so let's do the second entry (`1`), because it has a non-trivial number (4).

```python
>>> tree["GeoTracks/GeoTracks.fNpoints"].array()[1]
<Array [248, 8, 8, 8] type='4 * uint32'>
>>> tree["GeoTracks/GeoTracks.fPoints"].debug_array(1)
array([  1,   0,   0, ..., 246,  99, 155], dtype=uint8)
```

It seems that each of the four sub-entries has a different one-byte header. That's why an `AsJagged` isn't going to work, since it can only skip bytes at the beginning of an _entry_, not a _sub-entry_. The numbers in `fNpoints` actually count each 4-vector as 4, so let's start by integer-dividing them:

```python
>>> num_vectors = tree["GeoTracks/GeoTracks.fNpoints"].array() // 4
>>> num_vectors
<Array [[116], [62, 2, 2, ... 2, 3, 2], [116]] type='100 * var * uint32'>
```

For each entry, such as the entry number `1` that we're looking at now, we can get the raw bytes by

```python
>>> entry_raw_bytes = tree["GeoTracks/GeoTracks.fPoints"].debug_array(1)
```

I'm not sure, but I think that `debug_array` might be re-reading the whole TBasket from disk every time you ask for an entry, which would be a performance bug if we leave it that way. (**Edit:** it does and it would. That's why "`debug_array`" starts with the word "debug.") We'll have to get back to that. Let's just see if we can get the data out.

```python
>>> entry_vector_arrays = []
>>> pos = 0
>>> for n in num_vectors[1]:
...     pos += 1
...     entry_vector_arrays.append(
...         entry_raw_bytes[pos : pos + (n*4*8)].view(
...             np.dtype([("x", ">f8"),("y", ">f8"),("z", ">f8"),("t", ">f8")])
...         )
...     )
...     pos += n*4*8
```

Looking at these `entry_vector_arrays`, they look right. Getting all of these together—not just for entry `1`, but for all the entries—can be done with [ak.from_iter](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_iter.html).

Now we should address this problem of re-reading a whole TBasket when you only want one entry. Instead of `debug_array` for getting one entry, we can get the whole array with

```python
>>> raw_interpretation = uproot.AsJagged(uproot.AsDtype("u1"))
>>> raw_entries = tree["GeoTracks/GeoTracks.fPoints"].array(raw_interpretation)
>>> raw_entries
<Array [[1, 0, 0, 0, 0, ... 36, 96, 74, 108]] type='100 * var * uint8'>
```

Each entry in `raw_entries` is like `entry_raw_bytes` above. So the whole procedure from start to finish would be:

```python
import uproot
import numpy as np
import awkward as ak

tree = uproot.open("issue-553.root:pndsim")

num_vectors = tree["GeoTracks/GeoTracks.fNpoints"].array() // 4

raw_interpretation = uproot.AsJagged(uproot.AsDtype("u1"))
raw_entries = tree["GeoTracks/GeoTracks.fPoints"].array(raw_interpretation)

vector_arrays = []
for i, num in enumerate(num_vectors):
    entry_vector_arrays = []
    pos = 0
    for n in num:
        pos += 1
        recarray = np.asarray(raw_entries[i][pos : pos + (n*4*8)]).view(
            np.dtype([("x", ">f8"),("y", ">f8"),("z", ">f8"),("t", ">f8")])
        )
        entry_vector_arrays.append([
            {"x": v["x"], "y": v["y"], "z": v["z"], "t": v["t"]} for v in recarray
        ])
        pos += n*4*8
    vector_arrays.append(entry_vector_arrays)

vectors = ak.from_iter(vector_arrays)
```

where

```python
>>> vectors
<Array [[[{x: 0, y: 0, ... t: 5.32e-08}]]] type='100 * var * var * {"x": float64...'>
```

and

```python
>>> vectors[1, 1, 0]
<Record ... y: 4.04, z: 477, t: 1.88e-08} type='{"x": float64, "y": float64, "z"...'>
```

etc. This is not a solution to Uproot's reading of the file—I have no idea how the above could be encoded automatically. ROOT can do it because it has [TGeoTrack](https://root.cern.ch/doc/master/classTGeoTrack.html) with its custom streamers in its codebase. To do the same in Uproot, we'd need a specialized "`Model_TGeoTrack`" (as we do for some deep built-int classes like `TList`, but generally not for physics objects, particularly ones that have been split). I'll have to label this issue as "won't fix."

**Comment by rklasen** [comment]
Thanks for your help!

Setting the interpretation this way and iterating over the events seems to work, but unfortunately it's very slow for large files. So I think for now I'd still have to use a ROOT macro to read this file.

Still, thank you so much for your help!

**Comment by jpivarski** [comment]
This is something that could be sped up with [AwkwardForth](https://github.com/scikit-hep/awkward-1.0/wiki/AwkwardForth-documentation), but we're mostly using that for library code, rather than specific applications, so that the benefit-to-effort ratio is optimized. But, just pointing it out—cheers!
