### ISSUE TITLE
"extend" for read-only TTrees/merging user-defined content

### ISSUE THREAD

**Issue by kreczko** [scikit-hep/uproot4#563]
Apologies if I use the incorrect keywords - that might be a part of my problems ;).

At the lowest level I am trying to

```python
muon_py, muon_pz = input_tree.arrays(["Muon_Py", "Muon_Pz"], how=tuple)
muon_momentum = np.hypot(muon_py, muon_pz) # stand-in for arbitrary user function or awkward user data
# missing steps
# the below should work now
arrays = input_tree.arrays(["Muon_Py", "Muon_Pz", "Muon_momentum"], how=tuple)
```

Essentially, I would like to make use of the `.arrays` functionality for user-defined data, but `input_tree` is of type `Model_TTree_v19` - i.e. has no `extend` functionality.
I know I can use `aliases` for data that is well represented through an expression with existing data, but I am looking for a more general solution, .e.g

```python
arrays = input_tree.arrays(["Muon_Py", "Muon_Pz", "Muon_momentum"], how=tuple, extra_data={"Muon_momentum" : muon_momentum})
```
in a similar way that `numexpr.evaluate` uses `local_dict`.

- Is that something that is already possible?
- Would you recommend a workaround using `library.group` in a wrapper?
- Would such an extension to the functionality make sense at all from your design perspective?

**Comment by jpivarski** [comment]
I think you're making a mistake (that a lot of people make) in thinking of `TTree.arrays` as a method for computation: it's a method for reading data from disk. I should never have added the ability to evaluate expressions in that method, since this keeps coming up—not just your question, but others in which people are trying to shoehorn multi-statement calculations into the expression strings.

One tip-off is that you're comparing with `numexpr.evaluate`, which is a method (and a whole library) for computation. Uproot is just I/O; what computation it does (in the `expressions` and `cut` arguments) is just reading into temporary arrays and evaluating the expression in the string with Python. By adding the convenience of doing that in one line with the reading, I've created the expectation that this is how computation happens, and led a lot of people into unproductive alleys based on that expectation. This is a lesson for me in design: sometimes adding "shortcuts/conveniences/another way of doing something" can make things very inconvenient for users—I'm sorry about that!

If you want to make the second line possible because you want the `"Muon_momentum"` data to be in the file, so that you can give the file to someone else and maybe open it in ROOT, UnROOT, Laurelin, or another Uproot somewhere, the only way that's currently implemented is to read from one file/TTree and write to another. Modifying a TTree in place is not in-principle impossible, but it would be a major project to implement. (I wish I could find the GitHub Issues or Discussions where I've outlined what would be involved, but I can't find them.)

If you know all of the above (that `TTree.arrays` is meant for I/O, and `expressions`/`cuts` are really just evaluating in Python) and just want to be able to add variables to the context of the expressions that are evaluated in Python—that is, add `muon_momentum` to the dict of local or global variables that `TTree.arrays` passes into `eval`, then that would be a matter of getting it into this dict:

https://github.com/scikit-hep/uproot4/blob/027f7a11e4032eb26a05659e5fe1c9371c52f46d/src/uproot/language/python.py#L429

But _please don't!_ That would make the I/O-compute confusion even worse!
