### ISSUE TITLE
File writing with Unicode characters and compression

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot4#576]
While experimenting with Unicode characters, I ran into an issues when writing `.root` files containing objects with Unicode characters in their names. This might admittedly be an extremely niche use case, but I did not find Unicode characters mentioned in issues/discussion/documentation, and thought it may be useful to document this here if others run into the same thing.

The following works just fine:
```python
import uproot
import numpy as np

with uproot.recreate("tmp.root") as file:
    file["😀"] = np.histogram(np.random.normal(0, 1, 10))
```

I cannot read the resulting file though. This can be demonstrated by trying to access the histogram:
```python
import uproot
import numpy as np

with uproot.recreate("tmp.root") as file:
    file["😀"] = np.histogram(np.random.normal(0, 1, 10))
    file["😀"]
```
results in 
```pytb
Traceback (most recent call last):
  File "[...]/test.py", line 10, in <module>
    file["😀"]
  File "[...]/lib/python3.9/site-packages/uproot/writing/writable.py", line 957, in __getitem__
    return self._get_del_search(where, True)
  File "[...]/lib/python3.9/site-packages/uproot/writing/writable.py", line 950, in _get_del_search
    return self._get(item, cycle)
  File "[...]/lib/python3.9/site-packages/uproot/writing/writable.py", line 1018, in _get
    return readonlykey.get()
  File "[...]/lib/python3.9/site-packages/uproot/reading.py", line 2493, in get
    chunk, cursor = self.get_uncompressed_chunk_cursor()
  File "[...]/lib/python3.9/site-packages/uproot/reading.py", line 2549, in get_uncompressed_chunk_cursor
    uncompressed_chunk = uproot.compression.decompress(
  File "[...]/lib/python3.9/site-packages/uproot/compression.py", line 413, in decompress
    uncompressed_bytestring = decompressor.decompress(
  File "[...]/lib/python3.9/site-packages/uproot/compression.py", line 93, in decompress
    return zlib.decompress(data)
zlib.error: Error -3 while decompressing data: incorrect data check
```

I also tried `file[file.keys()[0]]`, which behaves in the same way.

The issue also appears when re-opening the file instead (in a new block via `uproot.open`), and also when using `ROOT` instead of `uproot`:
```
R__unzip: error -3 in inflate (zlib)
```

Since the error message suggests that this is compression-related, I tried writing with `compression=None`. This works fine, and can subsequently be read both with `uproot` and `ROOT`.

I opened this as a bug in case it actually is something related to encoding on the `uproot` side. If this type of pattern is not supported, perhaps it would be useful to check for the presence of Unicode characters when the decompression fails, and then inform the user about it? If the resulting files are broken (which the user may not know until trying to read them later), a check may even be useful when writing already (I do not know whether the resulting overhead may be a performance concern though).

software versions: `Python` 3.9.10, `uproot` 4.2.2, `ROOT` 6.24.06

**Comment by jpivarski** [comment]
It's not compression—that's where you see the error because decompression does a checksum and catches the error before you get any farther. The error is most likely a matter of Uproot's file writer declaring that a header has N bytes when it actually has M bytes, with the M ‒ N difference coming from the difference between the length of the string and the length of the bytestring.

```python
>>> len("😀")
1
>>> len("😀".encode("utf-8"))
4
```

Somewhere in src/uproot/writing, there is very likely a `len(name)` that should be `len(name.encode("utf-8"))`.

I tried it with π (`"\u03c0"`) because the emoji characters are in a newer table system of Unicode than the more basic non-ASCII characters. For instance, Java would get them wrong. The test with π revealed the same thing.

I also verified that ROOT can be used as a test of a properly made file:

```python
>>> import ROOT
>>> f = ROOT.TFile("tmp2.root", "RECREATE")
>>> h = ROOT.TH1F("\u03c0", "", 100, -5, 5)
>>> h.FillRandom("gaus", 10000)
>>> h.Write()
437
>>> f.Close()
```

```python
>>> import ROOT
>>> f = ROOT.TFile("tmp2.root")
>>> f.ls()
TFile**		tmp2.root	
 TFile*		tmp2.root	
  KEY: TH1F	π;1	
>>> h = f.Get("\u03c0")
>>> h.Draw()
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
```

So it's Uproot-writing's problem, and not "Uproot-reading and ROOT-reading"'s problem. At least that narrows it down.

**Comment by alexander-held** [comment]
> Somewhere in src/uproot/writing, there is very likely a `len(name)` that should be `len(name.encode("utf-8"))`.

Your idea looks to be correct, this seems to be the relevant part (for this example at least):
https://github.com/scikit-hep/uproot4/blob/8e3ab33c2d137079db53cd2c21b4c3ac7e1dcffc/src/uproot/writing/_cascade.py#L1605-L1607

diff:

```diff
- strings_size += (1 if len(name) < 255 else 5) + len(name)  
+ strings_size += (1 if len(name) < 255 else 5) + len(name.encode("utf-8"))
```

Perhaps the other lines would also have to change for other cases, they do not for this example though.

I am not sure to what extent this currently affects files written with Unicode characters and without compression. The histogram reading seems to be working fine in that case. I am surprised by this, but perhaps it is just a coincidence that this works anyway.

**Comment by jpivarski** [comment]
In fact, there are other places where it was already right, such as this one:

https://github.com/scikit-hep/uproot4/blob/8e3ab33c2d137079db53cd2c21b4c3ac7e1dcffc/src/uproot/writing/_cascadetree.py#L842-L846

(This is an advertisement for putting things into helper functions instead of doing them inline. Then you can catch all the places where you do the same sort of thing, and can ensure that it's right.)

I'll make a PR with this fix. Thanks for finding it!

**Comment by alexander-held** [comment]
Thank you!
