### ISSUE TITLE
arrays(library="pd") returns a tuple

### ISSUE THREAD

**Issue by dcervenkov** [scikit-hep/uproot4#583]
I have a ROOT file that I want to read using uproot and export a pandas DataFrame. The command I'm using is
```py
df = uproot.open("dvntuple.root")["Hlt2Dstp2D0Pip_D02KmKpPimPip_Tuple/DecayTree"].arrays(library="pd", entry_stop=8)
```
However, `df` is a `tuple` rather than `pandas.core.frame.DataFrame`. It's a tuple of two different DataFrames - `df[0]` has 8 rows and 893 columns, `df[1]` has 9 rows and 804 columns.

Is this expected?

I couldn't create a smaller test file as the file created by running the following command doesn't cause this behavior.
```sh
rooteventselector -l10 dvntuple.root:Hlt2Dstp2D0Pip_D02KmKpPimPip_Tuple/DecayTree mwe.root
```
The original largish file (1.7 GB) is available [here](https://cernbox.cern.ch/index.php/s/wnCckGSxgPxvMdB).

uproot 4.2.2

**Comment by jpivarski** [comment]
This is intentional; it's because the TBranches you're asking for are jagged with different length lists in the arrays. You're asking for all TBranches because you don't specify them. "Differently jagged" arrays can't be put into a single DataFrame because we represent the jaggedness in DataFrames via a MultiIndex, and a DataFrame can only have one index.

There's a more complete explanation in Discussion https://github.com/scikit-hep/uproot4/discussions/114.

**Comment by dcervenkov** [comment]
Excellent, thanks for the link to the more detailed discussion. However, after reading the discussion, I'm unsure what differences to expect between the individual DataFrames in the tuple, how many DataFrames to expect, and how many columns should each of them have.

**Comment by jpivarski** [comment]
You'll get the minimum possible number of DataFrames: all TBranches with alignable jaggedness will be in the same DataFrame, and they won't be in any of the other DataFrames (they'll be exclusively partitioned among DataFrames).

The non-jagged TBranches will be in all of the DataFrames, since their values need to get duplicated to make them fit into each of the DataFrames, and it's a different duplication in each.

If you want more control over the situation, specify an explicit list of TBranches to read. (You'll want that when you scale up to large datasets, anyway, since you'll need to start controlling memory use.) The TBranches that can all go in one DataFrame will be the ones that all correspond to the same particle: you'll have a muon DataFrame, an electron DataFrame, a jet DataFrame, etc. If you're selecting TBranches that you think all have the same jaggedness, such as all the muon attributes, but it returns more than one DataFrame, then they don't really have the same jaggedness and you've discovered a bug in your data preparation. (It's happened before, I can't find the link, but somebody was surprised by how the DataFrames split up and it turned out that a cut applied to one attribute was slightly different from the cut applied to all others. So it's good information!)

If this sounds cumbersome, you might want to avoid using Pandas. Pandas's range of data structures is not a good fit for general HEP data—we support it in Uproot because it's good for some simple cases. Ask yourself, for instance, how you're going to do combinatorics with the data in DataFrames, or some other step that you're going to need to do. All of the steps of applying cuts and making plots are exactly as easy to do outside of Pandas as within it. What Pandas adds is the ability to do SQL-like joins, which we don't do often in HEP.

**Comment by dcervenkov** [comment]
Thanks for the detailed reply. I did not produce the ROOT file and I think I need to look into how it is made to understand what jaggedness it has. A way to see which branches are jagged would help; does this exist?

I don't understand the argument why the non-jagged branches need to be in all DataFrames - I think that is the bit that confuses most users (judging by past issues). To me, it would make more sense if all the non-jagged entries were in one DataFrame and each jagged group in a separate DataFrame. 

Yep, I'll definitely load just a subset of branches for proper analysis, I was just surprised by the tuple of datasets when exploring.

I'm not adamant about using Pandas; your Awkward Arrays look very interesting in particular, however, the documentation has a lot of TODOs at this point, which is what's stopping me.

**Comment by dcervenkov** [comment]
Excellent, the `show()` method and *branch filtering based on interpretation* give me everything I need to do what I want. Thanks for the tips and helpful examples!

I understand your reasoning about the defaults, and while not what I'd choose, it's a fair choice. It'd be great if the workaround you posted here using the branch filtering based on interpretation could be mentioned in the documentation.

Regarding Awkward documentation - please don't remove the pages! The documentation overview looks great, and I'm aware that the project is relatively mature, but it is difficult to use it instead of, e.g., Pandas, if the documentation is not there. My first check was how to filter the data quickly, e.g., retain only events where `col1 > 3 and col2 < 0`. Then I saw that the [page](https://awkward-array.org/how-to-filter.html?highlight=cuts) doesn't exist yet, which means I'm back to Pandas for exploratory analysis (its `query()` is most useful and easy to use).

**Comment by jpivarski** [comment]
> My first check was how to filter the data quickly, e.g., retain only events where `col1 > 3 and col2 < 0`. Then I saw that the [page](https://awkward-array.org/how-to-filter.html?highlight=cuts) doesn't exist yet, which means I'm back to Pandas for exploratory analysis (its `query()` is most useful and easy to use).

Because that information is here: https://awkward-array.readthedocs.io/en/latest/_auto/ak.Array.html#filtering

The existence of a page that says "TODO" gives the impression that this information hasn't been written down, rather than being written down in another place. What I'm intending to do (c.f. https://github.com/scikit-hep/awkward-1.0/issues/1366#issuecomment-1065256551) is simplify its organization so that readers are funneled into the places where the things they're looking for have been written.

**Comment by dcervenkov** [comment]
Aha! Well, I did not realize that the documentation is in two places. Perhaps adding links to the old pages on the unfinished new pages could be a quick stop-gap solution. I'll comment on the issue you linked.
