### ISSUE TITLE
awkward_form() context arg is not optional

### ISSUE THREAD

**Issue by btovar** [scikit-hep/uproot4#614]
pr #611 consolidated most arguments to `awkward_form()` into a single dictionary `context`. From the wording of the documentation:

```python
context (dict): Context for the Form-generation; defaults are
                ``{"index_format": "i64", "header": False, "tobject_header": True, "breadcrumbs": ()}``.
                See below for context argument descriptions.
```

this seems to imply that context is optional, and that no other argument is required. If this is not the case, are callers of the function expected to provide `{}`, `None`, or as above `{"index_format": ...}` ?

From the current callers perspective that use the defaults, it would be easiest if context is optional, as no changes downstream would be needed.

(This issue became apparent with release 4.2.4.)

**Comment by jpivarski** [comment]
Those arguments are required; they were consolidated into a `context` because more will be added and we want to be able to do that without touching 400 `awkward_form` calls throughout the codebase.

Are you using this function? I had thought of it as an internal step in the process of executing `array`/`arrays`/`iterate`. Is there a particular class from which you call it, so that that class can be made to insert the defaults?

If _any_ of the `awkward_form` methods are being called, we could make `context=None` by default everywhere and have that be a signal to inject centrally maintained defaults.

--------

To directly answer your question, the required argument is the explicit dict given in the docstring, though that's not a friendly user interface (wasn't intended to be...).

**Comment by jpivarski** [comment]
PR #618 reverted the `Interpretation.awkward_form` argument list, which was merged into `main-v4` (and `main`), and `main-v4` was used to release [Uproot 4.3.0](https://pypi.org/project/uproot/4.3.0/), the first in the Uproot 4 bug-fix line. From our end, it seems to have worked; let me know if updating to the latest Uproot doesn't fix this problem.

**Comment by nsmith-** [comment]
We use some other private methods near this one:
https://github.com/CoffeaTeam/coffea/blob/master/coffea/nanoevents/mapping/uproot.py#L100-L105
Perhaps this should change as well?
