### ISSUE TITLE
Indices for array branches

### ISSUE THREAD

**Issue by alexander-held** [scikit-hep/uproot4#72]
I am working with a tree that contains branches which are vectors of floats:

```
>>> tree["weight_bTagSF_eigenvars_B_up"].show(interpretation_width=40)
name                 | typename             | interpretation
---------------------+----------------------+-----------------------------------------
weight_bTagSF_eigenv | std::vector<float>   | AsJagged(AsDtype('>f4'), header_bytes=10
```

In ROOT, I use `[0]` to obtain the first entry of the vector for every event:
```
root [8] nominal->Scan("weight_bTagSF_eigenvars_B_up[0]")
************************
*    Row   * weight_bT *
************************
*        0 * 1.0968146 *
*        1 * 0.8027607 *
*        2 * 1.0042166 *
*        3 * 1.0752149 *
*        4 * 0.9913491 *
*        5 * 0.7981501 *
```

To obtain the same values in `uproot4` (0.0.16), I need to use `[:,0]`:
```
>>> weight = "weight_bTagSF_eigenvars_B_up[:,0]"
>>> tree.arrays(weight)[weight]
<Array [1.1, 0.803, 1, ... 0.795, 0.808, 0.791] type='14992 * float32'>
```

Is this change in behavior on purpose? I'd like to turn user-provided strings into weights extracted from the file. In ROOT, such a string looks like `weight_bTagSF_eigenvars_B_up[0]*some_other_weight`. To handle this different convention, I would either translate the strings into what `uproot4` expects, or ask users to adopt this way of indexing. I was wondering whether there may exist some "ROOT-like" interpretation I can switch on?

I noticed that the above does not work with `library=np`:
```
>>> weight = "weight_bTagSF_eigenvars_B_up[:,0]"
>>> tree.arrays(weight, library="np")[weight]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 967, in arrays
    output = compute.compute_expressions(
  File "[...]/lib/python3.8/site-packages/uproot4/compute/python.py", line 347, in compute_expressions
    output[expression] = _expression_to_function(
  File "<dynamic>", line 1, in <lambda>
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
>>> tree.arrays("weight_bTagSF_eigenvars_B_up", library="np")["weight_bTagSF_eigenvars_B_up"]
array([array([1.0968146, 1.0773798, 1.0343741, 1.1100905, 1.0188507, 1.0471411],
      dtype=float32),
       array([0.8027608, 1.0142494, 0.9376403, 0.980236 , 0.9652771, 0.95773  ],
      dtype=float32),
       array([1.0042167 , 0.93642455, 1.0683353 , 0.9941829 , 0.9865473 ,
       1.0125985 ], dtype=float32),
       ...,
       array([0.7953308, 0.9993567, 0.9192695, 0.9617004, 0.9411704, 0.9501564],
      dtype=float32),
       array([0.80789626, 0.99212795, 0.9876958 , 1.0175581 , 1.0071241 ,
       0.99970514], dtype=float32),
       array([0.79134053, 0.99477154, 0.93990743, 0.95846075, 0.9771205 ,
       0.95926076], dtype=float32)], dtype=object)
```
I don't know whether this is a limitation of `numpy` or a bug. It is possible (but likely very inefficient) to extract the same information like this:
```
>>> np.asarray(tree.arrays("weight_bTagSF_eigenvars_B_up", library="np")["weight_bTagSF_eigenvars_B_up"].tolist())[:,0]
array([1.0968146 , 0.8027608 , 1.0042167 , ..., 0.7953308 , 0.80789626,
       0.79134053], dtype=float32)
```

**Comment by jpivarski** [comment]
> To obtain the same values in `uproot4` (0.0.16), I need to use `[:,0]`

The default `compute` environment for `arrays` is `uproot4.compute.python.ComputePython`, which treats the strings as Python code. This leaves room for a future "`ComputeTTFormula`", probably based on [formulate](https://github.com/scikit-hep/formulate), as well as the other analysis languages that are being developed. So this is intentional: the project of making `[0]` mean "the first item of every list" instead of "the first list" is an unstarted project. When such a thing exists, it would be a plug-in; perhaps the interface would be `compute="root"` instead of `compute="python"` (giving the compute environments string names, similar to the `library` argument).

> I noticed that the above does not work with `library=np`

With `library="np"`, you have even less functionality (and less performance) because NumPy does not have jagged arrays that can be indexed in such a way as to select the first item of each list without explicit loops. The `library="np"` option means, "I don't want to bring in any Awkward dependencies; give me a NumPy array, whatever it takes," and for a jagged array, that means

```python
np.array([np.array([1, 2, 3]), np.array([]), np.array([4, 5])], dtype="O")
```

When you slice this as `[:, 0]`, NumPy says, "IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed" because NumPy doesn't see the nested arrays as being an irregular dimension, but as random Python objects that it doesn't know anything about. That's why Awkward Array exists.

**Comment by alexander-held** [comment]
Thanks for the very clear explanation! Feel free to close, this provided all the information I was looking for.

**Comment by jpivarski** [comment]
Okay!
