### ISSUE TITLE
Uproot4 and Double32_t

### ISSUE THREAD

**Issue by fmazzasc** [scikit-hep/uproot4#85]
Hi,
I'm facing a weird issue when dealing with Double_32t with uproot4.
I have uploaded a small tree to reproduce the problem, in particular:

- `uproot4.open("test_tree.root")["Hyp3O2"]["RHyperTriton"]["m"].array()` converts the floating variable "m" as expected
-` uproot4.open("test_tree.root")["Hyp3O2"]["RHyperTriton"]["mppi_vert"].array() ` fails while converting the double32 variable "mppi_vert" with the following error: `AttributeError: 'NoneType' object has no attribute 'title'`

The link to the tree is:
- https://drive.google.com/file/d/14kF2gEKV7-eIbhSByd-F0cnUuVwrBopp/view?usp=sharing

Please note that the conversion with old uproot works nicely.
Any idea of what is happening here?

**Comment by jpivarski** [comment]
This will be fixed in PR #86. To recognize a branch as having Double32_t type, we either have to parse its TLeaf's title (if it's a TLeafD32) or its streamer's title (as in your case). In your case, no streamer was attached, but we expected one because the branch is known to have Double32_t type and its leaf is not a TLeafD32.

The fact that no streamer was attached was a bigger issue, and I'm grateful that you caught it and reported it. In Uproot 3, the Python class hierarchy for user-defined types like RHyperTriton exactly mirrored the C++ class hierarchy, but that led to some issues that were better resolved by a class merely _containing_ instances of its superclass. (See [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).) But that meant I was only looking in the RHyperTriton3O2 class for a field named `mppi_vert` when it was actually in the superclass, RHyperTriton. I had to extend the search to members of superclasses (which are now special members, rather than true Python superclasses) to find `mppi_vert`.

I was going to say that explains why it found `m`, but `m` is in the superclass as well. Oh: `m` is not a Double32_t; it didn't need a streamer to figure out its interpretation. That's why it worked.

The PR's tests pass and I'm merging it now. If you need this to be deployed as a new version, let me know and I'll do it. Otherwise, it's available as the master branch.

**Comment by fmazzasc** [comment]
Thanks a lot for the fix and the very accurate explanation! I don't need a new version for the fix urgently and I can easily use the master branch while waiting for the new release. Thanks again!
