### ISSUE TITLE
Allow access of a an open file-like object (root file within a `.tar.gz`)

### ISSUE THREAD

**Issue by rcross2** [scikit-hep/uproot4#98]
As far as I can tell, you can only open a root file via a path name?

I am working with a massive amount of files that are individually in `.tar.gz`s. I would like to access the root files within without explicitly extracting them first.

Right now I am doing this dance:

```python
with tarfile.open('/path/to/DATA.tar.gz', 'r') as tf:
    names = [x for x in tf.getnames() if x.endswith(".root")]
    for name in names:
        with tempfile.NamedTemporaryFile() as tmpfile:
            tinfo = tf.getmember(name)
            rootfile = tf.extractfile(tinfo)
            tmpfile.write(rootfile.read(-1))
            tmpfile.seek(0)
            branch = uproot4.lazy(f"{tmpfile.name}:path/to/branch")
            result = process(branch)
```

I would love if I could do something like (probably not fully correct but you get the idea):

```python
with tarfile.open('/path/to/DATA.tar.gz', 'r') as tf:
    names = [x for x in tf.getnames() if x.endswith(".root")]
    for name in names:
        tinfo = tf.getmember(name)
        rootfile = tf.extractfile(tinfo)
        uprootfile = uproot4.open(rootfile)
        branch = uprootfile.get("path/to/branch")
        result = process(branch)
```

**Comment by rcross2** [comment]
Amazing :)

**Comment by jpivarski** [comment]
What I'm amazed by is the fact that a file-like object can be used as a key of a dict (for the examples, not the implementation). Even in Python 2.7!

**Comment by rcross2** [comment]
As long as it's hashable... right?

**Comment by jpivarski** [comment]
That's what I'm surprised by. A file-like object is by definition mutable, and usually mutable objects are not hashable because they could have a different meaning at a later time. However, the "different meaning" for a file-like object is a different position in the file, which ordinary people would call "the same object," so it's sensible to make it hashable, hashing on the filename or something. Nevertheless, they _did_ it. Score +1 for Python!

**Comment by rcross2** [comment]
Awesome, working great!!! Much more streamlined and less writing to disk.

**Comment by jpivarski** [comment]
I'm glad it works for you!

There's a caveat written in the documentation that such objects can't be read in parallel because of the mutability thing. So only one reader-thread.

**Comment by rcross2** [comment]
Ok, I was having some difficulty opening _different_ files in parallel. My workers would just hang.

**Comment by jpivarski** [comment]
The thread-locality limits one thread to access one object—if the object passed to Uproot is independent of any others, then Uproot will handle it correctly, though slowly. Since we assume that the given object has internal state, we spawn exactly one thread for it: a thread can't seek the file to the wrong place while another thread is using it because there is only one thread.

However, if the object is not independent, then the behavior is undefined. If, for instance, the ExFileObject mutates the state of the TarFile and different threads are accessing different ExFileObjects from the same TarFile, they can mess each other up in unforeseeable ways. I don't know how Python's tarfile module is implemented. Its documentation says nothing about thread-safety, which is a crucial piece of information if you're going to be parallelizing access.

I doubt there would be appreciable performance loss if each ExFileObject is accessed through a different TarFile object. Doing so should guarantee that each has a distinct file pointer and can safely be used in threads. Each TarFile object would have to re-read the same tarball header/info metadata, but I doubt this would make a significant impact, given that it only stores the name, size, permissions, etc. of the files, right?

**Comment by rcross2** [comment]
Ah that makes sense! I will try using a different `TarFile` object for each process.
